<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	targetNamespace="http://www.mof.gov.cy" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified" 
	xmlns:olive="http://www.intracom.gr/olive" 
	xmlns:mof="http://www.mof.gov.cy">

	<xsd:annotation>
		<xsd:documentation xml:lang="EL">Το παρόν XML schema περιέχει
		ορισμούς τύπων οι οποίοι πρόκειται να χρησιμοποιηθούν
		για την αναπαράσταση δήλωσης Τ.Φ.1 Μισθωτού Φορολογικού Έτους 2024
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:import schemaLocation="olive-core.xsd" namespace="http://www.intracom.gr/olive"></xsd:import>
	<xsd:import namespace="http://www.intracom.gr/olive" schemaLocation="olive-core.xsd" />
	
	 <xsd:complexType name="epr1m2024KeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης Τ.Φ.1 Μισθωτού 2024 ανεξαρτήτως μέρους το οποίο δεν περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required" >
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου της δήλωσης Τ.Φ.1 Μισθωτού 2024 το οποίο δεν περιέχεται σε πίνακα. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                     <xsd:enumeration value="epr1mm1t0r1c1"/>
                     <xsd:enumeration value="epr1mm2t0r1c1"/>
                     <xsd:enumeration value="epr1mm2t0r2c1"/>
                     <xsd:enumeration value="epr1mm2t0r3c1"/>
                     <xsd:enumeration value="epr1mm3tar1c1"/>
                     <xsd:enumeration value="epr1mm3tar2c1"/>
                     <xsd:enumeration value="epr1mm3tb1r1c1"/>
					 <xsd:enumeration value="epr1mm3tb1r1c2"/>
					 <xsd:enumeration value="epr1mm3tb1r1c3"/>
					 <xsd:enumeration value="epr1mm3tb2r1c1"/>
					 <xsd:enumeration value="epr1mm3tb2r2c1"/>
					 <xsd:enumeration value="epr1mm3tb2r3c1"/>
					 <xsd:enumeration value="epr1mm3tb2r3c2"/>
					 <xsd:enumeration value="epr1mm3tb2r3c2b"/>
					 <xsd:enumeration value="epr1mm3tb2r3c2c"/>
					 <xsd:enumeration value="epr1mm3tb2r3c3"/>
					 <xsd:enumeration value="epr1mm3tb2r3c4"/>
					 <xsd:enumeration value="epr1mm3tb2r4c1"/>
					 <xsd:enumeration value="epr1mm3tb3r1c1"/>
					 <xsd:enumeration value="epr1mm3tb3r1c2"/>
                     <xsd:enumeration value="epr1mm4tar2c1"/>
                     <xsd:enumeration value="epr1mm4tar2c2"/>
                     <xsd:enumeration value="epr1mm4tar2c3"/>
                     <xsd:enumeration value="epr1mm4tar2c4"/>
                     <xsd:enumeration value="epr1mm4tar3c1"/>
                     <xsd:enumeration value="epr1mm4tar3c1y04"/>
                     <xsd:enumeration value="epr1mm4tar4c1"/>
                     <xsd:enumeration value="epr1mm4tar4c1b"/>
                     <xsd:enumeration value="epr1mm4tar5c1"/>
                     <xsd:enumeration value="epr1mm4tar8c1"/>
                     <xsd:enumeration value="epr1mm4tar9c1"/>
                     <xsd:enumeration value="epr1mm4tar9c1b"/>
                     <xsd:enumeration value="epr1mm4tar9c1c"/>
                     <xsd:enumeration value="epr1mm4tar10c1"/>
                     <xsd:enumeration value="epr1mm4tar11c1"/>
                     <xsd:enumeration value="epr1mm4tar11c1b"/>
                     <xsd:enumeration value="epr1mm4tar12c1"/>
                     <xsd:enumeration value="epr1mm4tar13c1"/>
                     <xsd:enumeration value="epr1mm4tar14c1"/>
                     <xsd:enumeration value="epr1mm4tar15c1"/>
                     <xsd:enumeration value="epr1mm4tar6c1"/>
                     <xsd:enumeration value="epr1mm4tar7c1"/>
                     <xsd:enumeration value="epr1mm4tbr2c1"/>
                     <xsd:enumeration value="epr1mm4tbr2c2"/>
                     <xsd:enumeration value="epr1mm4tbr2c3"/>
                     <xsd:enumeration value="epr1mm4tbr3c1"/>
                     <xsd:enumeration value="epr1mm4tbr4c1"/>
                     <xsd:enumeration value="epr1mm4tcr2c1"/>
                     <xsd:enumeration value="epr1mm4tcr2c2"/>
                     <xsd:enumeration value="epr1mm4tcr2c3"/>
                     <xsd:enumeration value="epr1mm4tcr2c4"/>
                     <xsd:enumeration value="epr1mm4tcr2c6"/>
                     <xsd:enumeration value="epr1mm4tcr2c7"/>
                     <xsd:enumeration value="epr1mm4tcr2c8"/>
                     <xsd:enumeration value="epr1mm4tdr2c1"/>
                     <xsd:enumeration value="epr1mm4tdr2c2"/>
                     <xsd:enumeration value="epr1mm4tdr2c3"/>
                     <xsd:enumeration value="epr1mm4ter2c1"/>
                     <xsd:enumeration value="epr1mm4ter2c2"/>
                     <xsd:enumeration value="epr1mm4ter2c3"/>
                     <xsd:enumeration value="epr1mm4ter2c4"/>
                     <xsd:enumeration value="epr1mm4tzr2c1"/>
                     <xsd:enumeration value="epr1mm4tzr2c2"/>
                     <xsd:enumeration value="epr1mm4tzr2c2a"/>
                     <xsd:enumeration value="epr1mm4tzr2c3"/>
                     <xsd:enumeration value="epr1mm4thr2c1"/>
                     <xsd:enumeration value="epr1mm4tjr2c1"/>
					 <xsd:enumeration value="epr1mm4tjr2c2"/>
					 <xsd:enumeration value="epr1mm4tjr2c3"/>
                     <xsd:enumeration value="epr1mm4tur2c1"/>
                     <xsd:enumeration value="epr1mm4tur2c2"/>
                     <xsd:enumeration value="epr1mm4tur2c3"/>
                     <xsd:enumeration value="epr1mm4tur2c4"/>
                     <xsd:enumeration value="epr1mm4tur3c1"/>
					 <xsd:enumeration value="epr1mm4tur3c2"/>
					 <xsd:enumeration value="epr1mm4tur3c3"/>
					 <xsd:enumeration value="epr1mm4tur4c1"/>
					 <xsd:enumeration value="epr1mm4tur4c2"/>
					 <xsd:enumeration value="epr1mm4tur4c3"/>
                     <xsd:enumeration value="epr1mm4tir1c1"/>
                     <xsd:enumeration value="epr1mm5tbr1c1"/>
                     <xsd:enumeration value="epr1mm5tbr2c1"/>
                     <xsd:enumeration value="epr1mm5tbr3c1"/>                     
                     <xsd:enumeration value="epr1mm5tbr3bc1"/>
                     <xsd:enumeration value="epr1mm5tbr3cc1"/>
                     <xsd:enumeration value="epr1mm5tbr4c1"/>
                     <xsd:enumeration value="epr1mm5tbr5c1"/>
                     <xsd:enumeration value="epr1mm5tcr2c1"/>
                     <xsd:enumeration value="epr1mm5tcr2c2"/>
                     <xsd:enumeration value="epr1mm5tcr2c3"/>
                     <xsd:enumeration value="epr1mm5tcr2c4"/>
                     <xsd:enumeration value="epr1mm5tdr3c1"/>
                     <xsd:enumeration value="epr1mm7t2ar2c1"/>
					 <xsd:enumeration value="epr1mm7t2ar2c2"/>
					 <xsd:enumeration value="epr1mm7t2ar2c3"/>
					 <xsd:enumeration value="epr1mm7t2ar2c4"/>
				     <xsd:enumeration value="epr1mm7t2ar2c5"/>
					 <xsd:enumeration value="epr1mm7t2ar2c6"/>
					 <xsd:enumeration value="epr1mm7t2ar2c7"/>
                     <xsd:enumeration value="epr1mm7t2ar1c1"/>
					 <xsd:enumeration value="epr1mm7t2ar1c2"/>
					 <xsd:enumeration value="epr1mm7t2ar1c3"/>
					 <xsd:enumeration value="epr1mm7t2ar1c4"/>
				     <xsd:enumeration value="epr1mm7t2ar1c5"/>
					 <xsd:enumeration value="epr1mm7t2ar1c6"/>
					 <xsd:enumeration value="epr1mm7t2ar1c7"/>
					 <xsd:enumeration value="epr1mm7t2br1c1"/>
					 <xsd:enumeration value="epr1mm7t2br1c2"/>
					 <xsd:enumeration value="epr1mm7t2br1c3"/>
					 <xsd:enumeration value="epr1mm7t2br1c4"/>
					 <xsd:enumeration value="epr1mm7t2br1c5"/>
					 <xsd:enumeration value="epr1mm7t2br1c6"/>
					 <xsd:enumeration value="epr1mm7t2br1c7"/>
					 <xsd:enumeration value="epr1mm7t2br2c1"/>
					 <xsd:enumeration value="epr1mm7t2br2c2"/>
					 <xsd:enumeration value="epr1mm7t2br2c3"/>
					 <xsd:enumeration value="epr1mm7t2br2c4"/>
					 <xsd:enumeration value="epr1mm7t2br2c5"/>
					 <xsd:enumeration value="epr1mm7t2br2c6"/>
					 <xsd:enumeration value="epr1mm7t2br2c7"/>
					 <xsd:enumeration value="epr1mm7t2br3c1"/>
					 <xsd:enumeration value="epr1mm7t2br3c2"/>
					 <xsd:enumeration value="epr1mm7t2br3c3"/>
					 <xsd:enumeration value="epr1mm7t2br3c4"/>
					 <xsd:enumeration value="epr1mm7t2br3c5"/>
					 <xsd:enumeration value="epr1mm7t2br3c6"/>
					 <xsd:enumeration value="epr1mm7t2br3c7"/>
					 <xsd:enumeration value="epr1mm7t2cr1c1"/>
					 <xsd:enumeration value="epr1mm7t2cr1c2"/>
					 <xsd:enumeration value="epr1mm7t2cr1c3"/>
					 <xsd:enumeration value="epr1mm7t2cr1c4"/>
					 <xsd:enumeration value="epr1mm7t2cr1c5"/>
					 <xsd:enumeration value="epr1mm7t2cr1c6"/>
					 <xsd:enumeration value="epr1mm7t2cr1c7"/>
					 <xsd:enumeration value="epr1mm7t2dr1c2"/>
					 <xsd:enumeration value="epr1mm7t2dr1c7"/>
					 <xsd:enumeration value="epr1mm7t2er1c1"/>
					 <xsd:enumeration value="epr1mm7t2er1c2"/>
					 <xsd:enumeration value="epr1mm7t2er1c3"/>
					 <xsd:enumeration value="epr1mm7t2er1c4"/>
					 <xsd:enumeration value="epr1mm7t2er1c5"/>
					 <xsd:enumeration value="epr1mm7t2er1c6"/>
					 <xsd:enumeration value="epr1mm7t2er1c7"/>
					 <xsd:enumeration value="epr1mm7t2er2c2"/>
					 <xsd:enumeration value="epr1mm7t2er2c7"/>
					 <xsd:enumeration value="epr1mm7t2er3c1"/>
					 <xsd:enumeration value="epr1mm7t2er3c2"/>
					 <xsd:enumeration value="epr1mm7t2er3c3"/>
					 <xsd:enumeration value="epr1mm7t2er3c4"/>
					 <xsd:enumeration value="epr1mm7t2er3c5"/>
					 <xsd:enumeration value="epr1mm7t2er3c6"/>
					 <xsd:enumeration value="epr1mm7t2er3c7"/>
					 <xsd:enumeration value="epr1mm7t2er4c1"/>
					 <xsd:enumeration value="epr1mm7t2er4c2"/>
					 <xsd:enumeration value="epr1mm7t2er4c3"/>
					 <xsd:enumeration value="epr1mm7t2er4c4"/>
					 <xsd:enumeration value="epr1mm7t2er4c5"/>
					 <xsd:enumeration value="epr1mm7t2er4c6"/>
					 <xsd:enumeration value="epr1mm7t2er4c7"/>
					 <xsd:enumeration value="epr1mm7t2fr1c1"/>
					 <xsd:enumeration value="epr1mm7t2fr1c2"/>
					 <xsd:enumeration value="epr1mm7t2fr1c3"/>
					 <xsd:enumeration value="epr1mm7t2fr1c4"/>
					 <xsd:enumeration value="epr1mm7t2fr1c5"/>
					 <xsd:enumeration value="epr1mm7t2fr1c6"/>
					 <xsd:enumeration value="epr1mm7t2fr1c7"/>
					 <xsd:enumeration value="epr1mm7t2gr1c1"/>
					 <xsd:enumeration value="epr1mm7t2gr1c2"/>
					 <xsd:enumeration value="epr1mm7t2gr1c3"/>
					 <xsd:enumeration value="epr1mm7t2gr1c4"/>
					 <xsd:enumeration value="epr1mm7t2gr1c5"/>
					 <xsd:enumeration value="epr1mm7t2gr1c6"/>
					 <xsd:enumeration value="epr1mm7t2gr1c7"/>
					 <xsd:enumeration value="epr1mm7t2gr2c1"/>
					 <xsd:enumeration value="epr1mm7t2gr2c2"/>
					 <xsd:enumeration value="epr1mm7t2gr2c3"/>
					 <xsd:enumeration value="epr1mm7t2gr2c4"/>
					 <xsd:enumeration value="epr1mm7t2gr2c5"/>
					 <xsd:enumeration value="epr1mm7t2gr2c6"/>
					 <xsd:enumeration value="epr1mm7t2gr2c7"/>
					 <xsd:enumeration value="epr1mm7t2gr3c1"/>
					 <xsd:enumeration value="epr1mm7t2gr3c2"/>
					 <xsd:enumeration value="epr1mm7t2gr3c3"/>
					 <xsd:enumeration value="epr1mm7t2gr3c4"/>
					 <xsd:enumeration value="epr1mm7t2gr3c5"/>
					 <xsd:enumeration value="epr1mm7t2gr3c6"/>
					 <xsd:enumeration value="epr1mm7t2gr3c7"/>
					 <xsd:enumeration value="epr1mm7t2hr1c1"/>
					 <xsd:enumeration value="epr1mm7t2hr1c2"/>
					 <xsd:enumeration value="epr1mm7t2hr1c3"/>
					 <xsd:enumeration value="epr1mm7t2hr1c4"/>
                     <xsd:enumeration value="epr1mm6t0r1c1"/>
                     <xsd:enumeration value="epr1mm6t0r2c1"/>
                     <xsd:enumeration value="epr1mm6t0r3c1"/>
                     <xsd:enumeration value="epr1mm6t0r4c1"/>
                     <xsd:enumeration value="epr1mm6t0r5c1"/>
                     <xsd:enumeration value="epr1mm6t0r6c1"/>
                     <xsd:enumeration value="epr1mm6t0r7c1"/>
                     <xsd:enumeration value="epr1mm6t0r7c2"/>
                     <xsd:enumeration value="epr1mm6t0r7c3"/>
                     <xsd:enumeration value="epr1mm7t0r1c1"/>
                     <xsd:enumeration value="epr1mm7t0r2c1"/>
                     <xsd:enumeration value="epr1mm7t0r3c1"/>
                     <xsd:enumeration value="epr1mm7t0r4ac1"/>
                     <xsd:enumeration value="epr1mm7t0r4bc1"/>
                     <xsd:enumeration value="epr1mm7t0r4cc1"/>
                     <xsd:enumeration value="epr1mm7t0r4c1"/>
                     <xsd:enumeration value="epr1mm7t0r5c1"/>
                     <xsd:enumeration value="epr1mm7t0r6c1"/>
                     <xsd:enumeration value="epr1mm7t0r7c1"/>
                     <xsd:enumeration value="epr1mm7t0r7ac1"/>
                     <xsd:enumeration value="epr1mm7t0r8c1"/>
                     <xsd:enumeration value="epr1mm7t0r8ac1"/>
                     <xsd:enumeration value="epr1mm7t0r9c1"/>
                     <xsd:enumeration value="epr1mm7t0r10c1"/>
                     <xsd:enumeration value="epr1mm7t0r11c1"/>
                     <xsd:enumeration value="epr1mm7t0r12ac1"/>
                     <xsd:enumeration value="epr1mm7t0r12c1"/>
                     <xsd:enumeration value="epr1mm7t0r13c2"/>
                     <xsd:enumeration value="epr1mm7t0r14c1"/>
                     <xsd:enumeration value="epr1mm7t0r15ac1"/>
                     <xsd:enumeration value="epr1mm7t0r15a2c1"/>
                     <xsd:enumeration value="epr1mm7t0r15bc1"/>
                     <xsd:enumeration value="epr1mm7t0r15cc1"/>
                     <xsd:enumeration value="epr1mm7t0r15dc1"/>
                     <xsd:enumeration value="epr1mm7t0r15dc2"/>
                     <xsd:enumeration value="epr1mm7t0r15c1"/>
                     <xsd:enumeration value="epr1mm7t0r16c1"/>
                     <xsd:enumeration value="epr1mm7t0r17c1"/>
                     <xsd:enumeration value="epr1mm7t0r18ac1"/>
                     <xsd:enumeration value="epr1mm7t0r18ac2"/>
                     <xsd:enumeration value="epr1mm7t0r18c1"/>
                     <xsd:enumeration value="epr1mm7t0r18c2"/>
                     <xsd:enumeration value="epr1mm7t0r18bc1"/>
                     <xsd:enumeration value="epr1mm7t0r18bc2"/>
                     <xsd:enumeration value="epr1mm7t0r19c2"/>
                     <xsd:enumeration value="epr1mm7t0r20ac1"/>
                     <xsd:enumeration value="epr1mm7t0r20c1"/>
                     <xsd:enumeration value="epr1mm7t0r21ac1"/>
                     <xsd:enumeration value="epr1mm7t0r21c1"/>
                     <xsd:enumeration value="epr1mm7t0r22c1"/>
                     <xsd:enumeration value="epr1mm7t0r22bc1"/>
                     <xsd:enumeration value="epr1mm7t0r23c1"/>
                     <xsd:enumeration value="epr1mm7t1r1c1"/>
                     <xsd:enumeration value="epr1mm7t1r1c2"/>
                     <xsd:enumeration value="epr1mm7t1r1c3"/>
                     <xsd:enumeration value="epr1mm7t1r1c4"/>
                     <xsd:enumeration value="epr1mm7t1r2c1"/>
                     <xsd:enumeration value="epr1mm7t1r2c2"/>
                     <xsd:enumeration value="epr1mm7t1r2c3"/>
                     <xsd:enumeration value="epr1mm7t1r2c4"/>
                     <xsd:enumeration value="epr1mm7t1r3c1"/>
                     <xsd:enumeration value="epr1mm7t1r3c2"/>
                     <xsd:enumeration value="epr1mm7t1r3c3"/>
                     <xsd:enumeration value="epr1mm7t1r3c4"/>
                     <xsd:enumeration value="epr1mm7t1r4c1"/>
                     <xsd:enumeration value="epr1mm7t1r4c2"/>
                     <xsd:enumeration value="epr1mm7t1r4c3"/>
                     <xsd:enumeration value="epr1mm7t1r4c4"/>
                     <xsd:enumeration value="epr1mm7t1r5c1"/>
                     <xsd:enumeration value="epr1mm7t1r5c2"/>
                     <xsd:enumeration value="epr1mm7t1r5c3"/>
                     <xsd:enumeration value="epr1mm7t1r5c4"/>
                     <xsd:enumeration value="epr1mm7t1r6c1"/>
                     <xsd:enumeration value="epr1mm7t1r6c2"/>
                     <xsd:enumeration value="epr1mm7t1r6c3"/>
                     <xsd:enumeration value="epr1mm7t1r6c4"/>
                     <xsd:enumeration value="epr1mm7t1r6ac1"/>
                     <xsd:enumeration value="epr1mm7t1r6ac2"/>
                     <xsd:enumeration value="epr1mm7t1r6ac3"/>
                     <xsd:enumeration value="epr1mm7t1r6ac4"/>
                     <xsd:enumeration value="epr1mm7t1r6ac5"/>
                     <xsd:enumeration value="epr1mm7t1r6ac6"/>
                     <xsd:enumeration value="epr1mm7t1r7c1"/>
                     <xsd:enumeration value="epr1mm7t1r7c1a"/>
                     <xsd:enumeration value="epr1mm7t1r7c1b"/>
                     <xsd:enumeration value="epr1mm7t1r7c2"/>
                     <xsd:enumeration value="epr1mm7t1r7c2a"/>
                     <xsd:enumeration value="epr1mm7t1r7c2b"/>
                     <xsd:enumeration value="epr1mm7t1r8c1"/>
                     <xsd:enumeration value="epr1mm7t1r8c1a"/>
                     <xsd:enumeration value="epr1mm7t1r8c1b"/>
                     <xsd:enumeration value="epr1mm7t1r8c2"/>
                     <xsd:enumeration value="epr1mm7t1r8c2a"/>
                     <xsd:enumeration value="epr1mm7t1r8c2b"/>
                     <xsd:enumeration value="epr1mm7t1r9c1"/>
                     <xsd:enumeration value="epr1mm7t1r9c1a"/>
                     <xsd:enumeration value="epr1mm7t1r9c1b"/>
                     <xsd:enumeration value="epr1mm7t1r9c2"/>
                     <xsd:enumeration value="epr1mm7t1r9c2a"/>
                     <xsd:enumeration value="epr1mm7t1r9c2b"/>
                     <xsd:enumeration value="epr1mm7t1r9ac1"/>
                     <xsd:enumeration value="epr1mm7t1r9ac1a"/>
                     <xsd:enumeration value="epr1mm7t1r9ac1b"/>
                     <xsd:enumeration value="epr1mm7t1r9ac2"/>
                     <xsd:enumeration value="epr1mm7t1r9ac2a"/>
                     <xsd:enumeration value="epr1mm7t1r9ac2b"/>
                     <xsd:enumeration value="epr1mm7t1r10c1"/>
                     <xsd:enumeration value="epr1mm7t1r10c1a"/>
                     <xsd:enumeration value="epr1mm7t1r10c1b"/>
                     <xsd:enumeration value="epr1mm7t1r10c2"/>
                     <xsd:enumeration value="epr1mm7t1r10c2a"/>
                     <xsd:enumeration value="epr1mm7t1r10c2b"/>
                     <xsd:enumeration value="epr1mm7t1r11c2"/>
                     <xsd:enumeration value="epr1mm7t1r12c1"/>
                     <xsd:enumeration value="epr1mm7t1r12c2"/>
                     <xsd:enumeration value="epr1mm8t0r1c1"/>
                     <xsd:enumeration value="epr1mm8t0r2c1"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
   
   <xsd:complexType name="epr1m2024GridKeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης Τ.Φ.1 Μισθωτού 2024 το οποίο περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required">
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου σε πίνακα της δήλωσης Τ.Φ.1 Μισθωτού 2024. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                     <xsd:enumeration value="epr1mm4tar1c1"/>
                     <xsd:enumeration value="epr1mm4tar1c2"/>
                     <xsd:enumeration value="epr1mm4tar1c3"/>
                     <xsd:enumeration value="epr1mm4tar1c3a"/>
                     <xsd:enumeration value="epr1mm4tar1c4"/>
                     <xsd:enumeration value="epr1mm4tar1c5"/>
                     <xsd:enumeration value="epr1mm4tar1c6"/>
                     <xsd:enumeration value="epr1mm4tar1c7"/>
                     <xsd:enumeration value="epr1mm4tar1c8"/>
                     <xsd:enumeration value="epr1mm4tar1c9"/>
                     <xsd:enumeration value="epr1mm4tar1c10"/>
                     <xsd:enumeration value="epr1mm4tbr1c1"/>
                     <xsd:enumeration value="epr1mm4tbr1c2"/>
                     <xsd:enumeration value="epr1mm4tbr1c3"/>
                     <xsd:enumeration value="epr1mm4tbr1c4"/>
                     <xsd:enumeration value="epr1mm4tbr1c5"/>
                     <xsd:enumeration value="epr1mm4tbr1c6"/>                     
                     <xsd:enumeration value="epr1mm4tcr1c1"/>
                     <xsd:enumeration value="epr1mm4tcr1c2"/>
                     <xsd:enumeration value="epr1mm4tcr1c3"/>
                     <xsd:enumeration value="epr1mm4tcr1c4"/>
                     <xsd:enumeration value="epr1mm4tcr1c5"/>
                     <xsd:enumeration value="epr1mm4tcr1c6"/>
                     <xsd:enumeration value="epr1mm4tcr1c7"/>
                     <xsd:enumeration value="epr1mm4tcr1c8"/>
                     <xsd:enumeration value="epr1mm4tcr1c9"/>
                     <xsd:enumeration value="epr1mm4tcr1c9a"/>
                     <xsd:enumeration value="epr1mm4tcr1c10"/>
                     <xsd:enumeration value="epr1mm4tcr1c11"/>
                     <xsd:enumeration value="epr1mm4tcr1c12"/>
                     <xsd:enumeration value="epr1mm4tcr1c13"/>
                     <xsd:enumeration value="epr1mm4tcr1c15"/>	
                     <xsd:enumeration value="epr1mm4tcr1c16"/>
                     <xsd:enumeration value="epr1mm4tcr1c17"/>
                     <xsd:enumeration value="epr1mm4tdr1c1"/>
                     <xsd:enumeration value="epr1mm4tdr1c2"/>
                     <xsd:enumeration value="epr1mm4tdr1c3"/>
                     <xsd:enumeration value="epr1mm4tdr1c4"/>
                     <xsd:enumeration value="epr1mm4tdr1c5"/>
                     <xsd:enumeration value="epr1mm4tdr1c6"/>
                     <xsd:enumeration value="epr1mm4tdr1c7"/>
                     <xsd:enumeration value="epr1mm4tdr1c8"/>
                     <xsd:enumeration value="epr1mm4tdr1c9"/>
                     <xsd:enumeration value="epr1mm4tdr1c10"/>
                     <xsd:enumeration value="epr1mm4tdr1c11"/>
                     <xsd:enumeration value="epr1mm4tdr1c12"/>
                     <xsd:enumeration value="epr1mm4tdr1c13"/>
                     <xsd:enumeration value="epr1mm4tdr1c14"/>
                     <xsd:enumeration value="epr1mm4tdr1c15"/>
                     <xsd:enumeration value="epr1mm4tdr1c16"/>
                     <xsd:enumeration value="epr1mm4ter1c1"/>
                     <xsd:enumeration value="epr1mm4ter1c2"/>
                     <xsd:enumeration value="epr1mm4ter1c3"/>
                     <xsd:enumeration value="epr1mm4ter1c5"/>
                     <xsd:enumeration value="epr1mm4ter1c6"/>
                     <xsd:enumeration value="epr1mm4ter1c7"/>
                     <xsd:enumeration value="epr1mm4ter1c7a"/>
                     <xsd:enumeration value="epr1mm4ter1c8"/>
                     <xsd:enumeration value="epr1mm4ter1c9"/>
                     <xsd:enumeration value="epr1mm4ter1c10"/>
                     <xsd:enumeration value="epr1mm4ter1c11"/>
                     <xsd:enumeration value="epr1mm4tzr1c1"/>
                     <xsd:enumeration value="epr1mm4tzr1c1b"/>
                     <xsd:enumeration value="epr1mm4tzr1c2"/>
                     <xsd:enumeration value="epr1mm4tzr1c3"/>
                     <xsd:enumeration value="epr1mm4tzr1c4"/>
                     <xsd:enumeration value="epr1mm4tzr1c5"/>
                     <xsd:enumeration value="epr1mm4tzr1c5a"/>
                     <xsd:enumeration value="epr1mm4tzr1c6"/>
                     <xsd:enumeration value="epr1mm4tzr1c7"/>
                     <xsd:enumeration value="epr1mm4thr1c1"/>
                     <xsd:enumeration value="epr1mm4thr1c2"/>
                     <xsd:enumeration value="epr1mm4thr1c3"/>
                     <xsd:enumeration value="epr1mm4thr1c4"/>
                     <xsd:enumeration value="epr1mm4thr1c5"/>
                     <xsd:enumeration value="epr1mm4tjr1c1"/>
					 <xsd:enumeration value="epr1mm4tjr1c2"/>
					 <xsd:enumeration value="epr1mm4tjr1c3"/>
					 <xsd:enumeration value="epr1mm4tjr1c4"/>
					 <xsd:enumeration value="epr1mm4tjr1c5"/>
					 <xsd:enumeration value="epr1mm4tjr1c6"/>
					 <xsd:enumeration value="epr1mm4tjr1c7"/>
					 <xsd:enumeration value="epr1mm4tjr1c8"/>
                     <xsd:enumeration value="epr1mm4tur1c1"/>
                     <xsd:enumeration value="epr1mm4tur1c2"/>
                     <xsd:enumeration value="epr1mm4tur1c3"/>
                     <xsd:enumeration value="epr1mm4tur1c4"/>
                     <xsd:enumeration value="epr1mm4tur1c5"/>
                     <xsd:enumeration value="epr1mm4tur1c6"/>
                     <xsd:enumeration value="epr1mm4tur1c7"/>
                     <xsd:enumeration value="epr1mm4tur1c8"/>
                     <xsd:enumeration value="epr1mm5tcr1c1"/>
                     <xsd:enumeration value="epr1mm5tcr1c1b"/>
                     <xsd:enumeration value="epr1mm5tcr1c1c"/>
                     <xsd:enumeration value="epr1mm5tcr1c1d"/>
                     <xsd:enumeration value="epr1mm5tcr1c2"/>
                     <xsd:enumeration value="epr1mm5tcr1c3"/>
                     <xsd:enumeration value="epr1mm5tcr1c4"/>
                     <xsd:enumeration value="epr1mm5tcr1c5"/>
                     <xsd:enumeration value="epr1mm5tdr1c1"/>
                     <xsd:enumeration value="epr1mm5tdr1c2"/>
                     <xsd:enumeration value="epr1mm5tdr1c3"/>
                     <xsd:enumeration value="epr1mm5tdr1c4"/>
                     <xsd:enumeration value="epr1mm5tdr1c5"/>
                     <xsd:enumeration value="epr1mm5tdr1c6"/>
                     <xsd:enumeration value="epr1mm5tdr1c7"/>
                     <xsd:enumeration value="epr1mm5tdr2c1"/>
                     <xsd:enumeration value="epr1mm5tdr2c2"/>
                     <xsd:enumeration value="epr1mm5tdr2c3"/>
                     <xsd:enumeration value="epr1mm5tdr2c4"/>
                     <xsd:enumeration value="epr1mm5tdr2c5"/>
                     <xsd:enumeration value="epr1mm5tdr2c6"/>
                     <xsd:enumeration value="epr1mm5tdr2c7"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
	
</xsd:schema>
