<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.mof.gov.cy" xmlns:mof="http://www.mof.gov.cy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:olive="http://www.intracom.gr/olive" elementFormDefault="qualified">

	<xsd:annotation>
		<xsd:documentation xml:lang="EL">
		XML Schema για την αναπαράσταση δηλώσεων ΕΠΡ614 Ενοικίων Φορολογικού Έτους 2024 το οποίο υποβάλλεται από τελικό χρήστη. 
		To παρόν schema προορίζεται για δημόσια χρήση.</xsd:documentation>
	</xsd:annotation>

	<xsd:include schemaLocation="cy-core.xsd" />
	<xsd:import namespace="http://www.intracom.gr/olive" schemaLocation="olive-core.xsd" />
   <xsd:include schemaLocation="cy-epr614-2024-keys.xsd" />

	<xsd:simpleType name="epr614DocumentVersionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση της έκδοσης υλοποίησης του παρόντος XML Schema</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="2024-1.0" />
		</xsd:restriction>
	</xsd:simpleType>
   
   <xsd:complexType name="customEpr6142024GridRowType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Αναπαριστά γραμμή πίνακα σε δήλωση epr614</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="field" type="mof:epr6142024GridKeyValuePairType" maxOccurs="100" />
		</xsd:sequence>
		<xsd:attribute name="number" type="xsd:long" use="required" />
	</xsd:complexType>
   
   <xsd:complexType name="customEpr6142024GridSectionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Αναπαριστά πίνακα epr614</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="row" type="mof:customEpr6142024GridRowType" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required" />
	</xsd:complexType>
   
	<xsd:complexType name="epr614GridSectionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση πίνακα της δήλωσης</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
         <xsd:restriction base="mof:customEpr6142024GridSectionType">
				<xsd:sequence>
					<xsd:element name="row" type="mof:customEpr6142024GridRowType" maxOccurs="unbounded">
						<xsd:unique name="unique-epr614-grid-row-field-key">
							<xsd:annotation>
								<xsd:documentation xml:lang="EL">Αποτρέπει την παρουσία δυο ίδιων κωδικών, μεταξύ των ζευγών (κωδικός-τιμή) στις γραμμές κάθε πίνακα</xsd:documentation>
							</xsd:annotation>
							<xsd:selector xpath="mof:field" />
							<xsd:field xpath="@key" />
						</xsd:unique>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="id" use="required">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Αναπαριστά των κωδικό του ο οποίος προσδιορίζει με μοναδιαίο τρόπο κάθε πίνακα της δήλωσης. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
					</xsd:annotation>
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="epr614m1t1r1" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
          </xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="epr614DeclType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου δήλωσης ΕΠΡ614 Ενοικίων</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="period" type="olive:date-rangeType">
				<xsd:annotation>
					<xsd:documentation xml:lang="EL">H περίοδος για την οποία πραγματοποιήθηκε η δήλωση</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="field" type="mof:epr6142024KeyValuePairType" maxOccurs="300">
				<xsd:annotation>
					<xsd:documentation xml:lang="EL">Αναπαριστά ζεύγος της μορφής κωδικός πεδίου - τιμή. Με το τρόπο αυτό απεικονίζεται κάθε πεδίο της δήλωσης ανεξαρτήτως μέρους το οποίο δεν περιέχεται σε πίνακα.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="grid" type="mof:epr614GridSectionType" minOccurs="0" maxOccurs="48">
				<xsd:unique name="unique-epr614-grid-row-num">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι οι γραμμές του κάθε πίνακα θα προσδιορίζονται από μοναδικό αριθμό γραμμής</xsd:documentation>
					</xsd:annotation>
					<xsd:selector xpath="mof:row" />
					<xsd:field xpath="@number" />
				</xsd:unique>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="version" type="mof:epr614DocumentVersionType" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="EL">Έκδοσης υλοποίησης του παρόντος XML Schema</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:element name="epr614-declarations">
		<xsd:annotation><xsd:documentation xml:lang="EL">
		Ορισμός τύπου για την αναπαράσταση μιας ή περισσότερων  (ενδεικτικά έχει τεθεί άνω όριο 20) δηλώσεων ΕΠΡ614 
		</xsd:documentation> </xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="epr614-declaration" maxOccurs="20">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Δήλωση ΕΠΡ614 Ενοικίων</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:extension base="mof:epr614DeclType">
								<xsd:attribute name="taxpayer" type="mof:TICType" use="required"></xsd:attribute>
							</xsd:extension>
						</xsd:complexContent>
					</xsd:complexType>
					<xsd:key name="unique-epr614-field-key">
						<xsd:annotation>
							<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι κάθε ζεύγος, της μορφής κωδικός πεδίου - τιμή, το οποίο αναπαριστά πεδίο της δήλωσης εκτός πίνακα θα εμφανίζεται το πολύ μια φορά.</xsd:documentation>
						</xsd:annotation>
						<xsd:selector xpath="mof:field" />
						<xsd:field xpath="@key" />
					</xsd:key>
					<xsd:key name="unique-epr614-grid-id">
						<xsd:annotation>
							<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι κάθε πίνακας θα εμφανίζεται το πολύ μια φορά σε κάθε δήλωση</xsd:documentation>
						</xsd:annotation>
						<xsd:selector xpath="mof:grid" />
						<xsd:field xpath="@id" />
					</xsd:key>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:key name="unique-epr614-per-taxpayer">
			<xsd:annotation>
				<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι έχουμε μοναδικές δηλώσεις ΕΠΡ614 ανά φορολογούμενο</xsd:documentation>
			</xsd:annotation>
			<xsd:selector xpath="mof:epr614-declaration" />
			<xsd:field xpath="@taxpayer" />
		</xsd:key>
	</xsd:element>

</xsd:schema>