<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.mof.gov.cy" xmlns:mof="http://www.mof.gov.cy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:olive="http://www.intracom.gr/olive" elementFormDefault="qualified">
	<xsd:annotation>
		<xsd:documentation xml:lang="EL">XML Schema για την αναπαράσταση δήλωσης Τ.Φ.1 Μισθωτού Φορολογικού Έτους 2024 το οποίο υποβάλλεται από τελικό χρήστη. To παρόν schema προορίζεται για δημόσια χρήση.</xsd:documentation>
	</xsd:annotation>

	<xsd:include schemaLocation="cy-core.xsd" />
	<xsd:import namespace="http://www.intracom.gr/olive" schemaLocation="olive-core.xsd" />
   <xsd:include schemaLocation="cy-epr1m-2024-keys.xsd" />
   
	<xsd:simpleType name="epr1mDocumentVersionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση της έκδοσης υλοποίησης του παρόντος XML Schema</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="2024-1.0" />
		</xsd:restriction>
	</xsd:simpleType>

   <xsd:complexType name="customEpr1m2024GridRowType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Αναπαριστά γραμμή πίνακα σε δήλωση Τ.Φ.1 Μισθωτού 2024</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="field" type="mof:epr1m2024GridKeyValuePairType" maxOccurs="100" />
		</xsd:sequence>
		<xsd:attribute name="number" type="xsd:long" use="required" />
	</xsd:complexType>
   
   <xsd:complexType name="customEpr1m2024GridSectionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Αναπαριστά πίνακα Τ.Φ.1 Μισθωτού 2024</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="row" type="mof:customEpr1m2024GridRowType" maxOccurs="100" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string" use="required" />
	</xsd:complexType>
   
	<xsd:complexType name="epr1mGridSectionType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση πίνακα της δήλωσης</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:restriction base="mof:customEpr1m2024GridSectionType">
				<xsd:sequence>
					<xsd:element name="row" type="mof:customEpr1m2024GridRowType" maxOccurs="100">
						<xsd:unique name="unique-epr1m-grid-row-field-key">
							<xsd:annotation>
								<xsd:documentation xml:lang="EL">Αποτρέπει την παρουσία δυο ίδιων κωδικών, μεταξύ των ζευγών (κωδικός-τιμή) στις γραμμές κάθε πίνακα</xsd:documentation>
							</xsd:annotation>
							<xsd:selector xpath="mof:field" />
							<xsd:field xpath="@key" />
						</xsd:unique>
					</xsd:element>
				</xsd:sequence>
				<xsd:attribute name="id" use="required">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Αναπαριστά των κωδικό του ο οποίος προσδιορίζει με μοναδιαίο τρόπο κάθε πίνακα της δήλωσης. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
					</xsd:annotation>
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="epr1mm4tar1" />
							<xsd:enumeration value="epr1mm4tbr1" />
							<xsd:enumeration value="epr1mm4tcr1" />
							<xsd:enumeration value="epr1mm4tdr1" />
							<xsd:enumeration value="epr1mm4ter1" />
							<xsd:enumeration value="epr1mm4tzr1" />
							<xsd:enumeration value="epr1mm4thr1" />
							<xsd:enumeration value="epr1mm4tjr1" />
							<xsd:enumeration value="epr1mm4tur1" />
							<xsd:enumeration value="epr1mm5tcr1" />
							<xsd:enumeration value="epr1mm5tdr1" />
							<xsd:enumeration value="epr1mm5tdr2" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="epr1mDeclType">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου δήλωσης Τ.Φ.1 Μισθωτού</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>

			<xsd:element name="period" type="olive:date-rangeType">
				<xsd:annotation>
					<xsd:documentation xml:lang="EL">H περίοδος για την οποία πραγματοποιήθηκε η δήλωση</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="field" type="mof:epr1m2024KeyValuePairType" maxOccurs="500">
				<xsd:annotation>
					<xsd:documentation xml:lang="EL">Αναπαριστά ζεύγος της μορφής κωδικός πεδίου - τιμή. Με το τρόπο αυτό απεικονίζεται κάθε πεδίο της δήλωσης ανεξαρτήτως μέρους το οποίο δεν περιέχεται σε πίνακα.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="grid" type="mof:epr1mGridSectionType" minOccurs="0" maxOccurs="20">
				<xsd:unique name="unique-epr1m-grid-row-num">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι οι γραμμές του κάθε πίνακα θα προσδιορίζονται από μοναδικό αριθμό γραμμής</xsd:documentation>
					</xsd:annotation>
					<xsd:selector xpath="mof:row" />
					<xsd:field xpath="@number" />
				</xsd:unique>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="version" type="mof:epr1mDocumentVersionType" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="EL">Έκδοσης υλοποίησης του παρόντος XML Schema</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:element name="epr1m-declarations">
		<xsd:annotation>
			<xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση μιας ή περισσότερων (ενδεικτικά έχει τεθεί άνω όριο 20) δηλώσεων Τ.Φ.1 Μισθωτού</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="epr1m-declaration" maxOccurs="20">
					<xsd:annotation>
						<xsd:documentation xml:lang="EL">Δήλωση Τ.Φ.1 Μισθωτού</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:complexContent>
							<xsd:extension base="mof:epr1mDeclType">
								<xsd:attribute name="taxpayer" type="mof:TICType" use="required"></xsd:attribute>
							</xsd:extension>
						</xsd:complexContent>
					</xsd:complexType>
					<xsd:key name="unique-epr1m-field-key">
						<xsd:annotation>
							<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι κάθε ζεύγος, της μορφής κωδικός πεδίου - τιμή, το οποίο αναπαριστά πεδίο της δήλωσης εκτός πίνακα θα εμφανίζεται το πολύ μια φορά.</xsd:documentation>
						</xsd:annotation>
						<xsd:selector xpath="mof:field" />
						<xsd:field xpath="@key" />
					</xsd:key>
					<xsd:key name="unique-epr1m-grid-id">
						<xsd:annotation>
							<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι κάθε πίνακας θα εμφανίζεται το πολύ μια φορά σε κάθε δήλωση</xsd:documentation>
						</xsd:annotation>
						<xsd:selector xpath="mof:grid" />
						<xsd:field xpath="@id" />
					</xsd:key>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
		<xsd:key name="unique-epr1m-per-taxpayer">
			<xsd:annotation>
				<xsd:documentation xml:lang="EL">Περιορισμός ο οποίος εξασφαλίζει ότι έχουμε μοναδικές δηλώσεις Τ.Φ.1 Μισθωτού ανά φορολογούμενο</xsd:documentation>
			</xsd:annotation>
			<xsd:selector xpath="mof:epr1m-declaration" />
			<xsd:field xpath="@taxpayer" />
		</xsd:key>
	</xsd:element>

</xsd:schema>
