<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	targetNamespace="http://www.mof.gov.cy" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified" 
	xmlns:olive="http://www.intracom.gr/olive" 
	xmlns:mof="http://www.mof.gov.cy">

	<xsd:annotation>
		<xsd:documentation xml:lang="EL">Το παρόν XML schema περιέχει
		ορισμούς τύπων οι οποίοι πρόκειται να χρησιμοποιηθούν
		για την αναπαράσταση δήλωσης ΕΠΡ4 εταιρείας Φορολογικού Έτους 2024
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:import schemaLocation="olive-core.xsd" namespace="http://www.intracom.gr/olive"></xsd:import>
	<xsd:import namespace="http://www.intracom.gr/olive" schemaLocation="olive-core.xsd" />
	
	 <xsd:complexType name="epr42024KeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης ΕΠΡ4 2024 ανεξαρτήτως μέρους το οποίο δεν περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required" >
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου της δήλωσης ΕΠΡ4 2024 το οποίο δεν περιέχεται σε πίνακα. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                     <xsd:enumeration value="epr4m1t0r1c1"/>
                     <xsd:enumeration value="epr4m1tar1c1n"/>
                     <xsd:enumeration value="epr4m1tbr1c1n"/>
                     <xsd:enumeration value="epr4m1tbr2c1n"/>
                     <xsd:enumeration value="epr4m1tbr2c2n"/>
                     <xsd:enumeration value="epr4m1tbr2c3n"/>
                     <xsd:enumeration value="epr4m1tcr1c1n"/>
                     <xsd:enumeration value="epr4m1tcr2c1n"/>
                     <xsd:enumeration value="epr4m1tcr2c2n"/>
                     <xsd:enumeration value="epr4m1tcr2c3n"/>
                     <xsd:enumeration value="epr4m1tdr1c1n"/>
                     <xsd:enumeration value="epr4m1tdr1c2n"/>
                     <xsd:enumeration value="epr4m1tdr2c1n"/>
                     <xsd:enumeration value="epr4m1tdr2c2n"/>
                     <xsd:enumeration value="epr4m1tdr2c3n"/>
                     <xsd:enumeration value="epr4m1ter1c1n"/>
                     <xsd:enumeration value="epr4m1ter1c2n"/>
                     <xsd:enumeration value="epr4m1ter2c1n"/>
                     <xsd:enumeration value="epr4m1ter2c2n"/>
                     <xsd:enumeration value="epr4m1ter3c2n"/>
                     <xsd:enumeration value="epr4m2tar1c1n"/>
                     <xsd:enumeration value="epr4m2tar2c1n"/>
                     <xsd:enumeration value="epr4m2tar2c2n"/>
                     <xsd:enumeration value="epr4m2tbr1c1n"/>
                     <xsd:enumeration value="epr4m2tbr2c1n"/>
                     <xsd:enumeration value="epr4m2tbr2c2n"/>
                     <xsd:enumeration value="epr4m2tcr1c1n"/>
                     <xsd:enumeration value="epr4m2tcr2c1n"/>
                     <xsd:enumeration value="epr4m2tcr2c2n"/>
                     <xsd:enumeration value="epr4m1ter1c1"/>
                     <xsd:enumeration value="epr4m1ter2c1"/>
                     <xsd:enumeration value="epr4m1ter2ac1"/>
                     <xsd:enumeration value="epr4m1ter2bc1"/>
                     <xsd:enumeration value="epr4m1ter3c1"/>
                     <xsd:enumeration value="epr4m1ter3c2"/>
                     <xsd:enumeration value="epr4m1ter3c3"/>
                     <xsd:enumeration value="epr4m1ter3c4"/>
                     <xsd:enumeration value="epr4m1ter3bc1"/>
                     <xsd:enumeration value="epr4m1ter3bc2"/>
                     <xsd:enumeration value="epr4m1ter3bc3"/>
                     <xsd:enumeration value="epr4m1ter3bc4"/>
                     <xsd:enumeration value="epr4m1ter4c1"/>
                     <xsd:enumeration value="epr4m1ter4c2"/>
                     <xsd:enumeration value="epr4m1ter4c3"/>
                     <xsd:enumeration value="epr4m1ter5c1"/>
                     <xsd:enumeration value="epr4m1ter5c2"/>
                     <xsd:enumeration value="epr4m1ter5c3"/>
                     <xsd:enumeration value="epr4m1ter6c1"/>
                     <xsd:enumeration value="epr4m1ter6c2"/>
                     <xsd:enumeration value="epr4m1ter6c3"/>
                     <xsd:enumeration value="epr4m1ter7c1"/>
                     <xsd:enumeration value="epr4m1ter7c2"/>
                     <xsd:enumeration value="epr4m1ter7c3"/>
                     <xsd:enumeration value="epr4m1ter8c1"/>
                     <xsd:enumeration value="epr4m1ter8c2"/>
                     <xsd:enumeration value="epr4m1ter8c3"/>
                     <xsd:enumeration value="epr4m1ter9c1"/>
                     <xsd:enumeration value="epr4m1ter9c2"/>
                     <xsd:enumeration value="epr4m1ter9c3"/>
                     <xsd:enumeration value="epr4m1ter11c1"/>
                     <xsd:enumeration value="epr4m1ter11c2"/>
                     <xsd:enumeration value="epr4m1ter14c1"/>
                     <xsd:enumeration value="epr4m1ter15c1"/>
                     <xsd:enumeration value="epr4m1ter15ac1"/>
                     <xsd:enumeration value="epr4m1ter16c1"/>
                     <xsd:enumeration value="epr4m1ter17c1"/>
                     <xsd:enumeration value="epr4m1ter18c1"/>
                     <xsd:enumeration value="epr4m1ter19c1"/>
                     <xsd:enumeration value="epr4m1ter20c1"/>
                     <xsd:enumeration value="epr4m1ter21c1"/>
                     <xsd:enumeration value="epr4m1ter24c1"/>
                     <xsd:enumeration value="epr4m1ter25c1"/>
                     <xsd:enumeration value="epr4m1ter26c1"/>
                     <xsd:enumeration value="epr4m1ter27c1"/>
                     <xsd:enumeration value="epr4m1ter28c1"/>
                     <xsd:enumeration value="epr4m1ter29c1"/>
                     <xsd:enumeration value="epr4m1ter30c1"/>
                     <xsd:enumeration value="epr4m1ter31c1"/>
                     <xsd:enumeration value="epr4m1ter32c1"/>
                     <xsd:enumeration value="epr4m1ter33c1"/>
                     <xsd:enumeration value="epr4m1tfr1c1"/>
                     <xsd:enumeration value="epr4m1tfr2c1"/>
                     <xsd:enumeration value="epr4m1tfr3c1"/>
                     <xsd:enumeration value="epr4m1tfr4c1"/>
                     <xsd:enumeration value="epr4m1tfr5c1"/>
                     <xsd:enumeration value="epr4m2ta1r1ac1"/>
                     <xsd:enumeration value="epr4m2ta1r1ac2"/>
                     <xsd:enumeration value="epr4m2ta1r1ac3"/>
                     <xsd:enumeration value="epr4m2ta1r1ac4"/>
                     <xsd:enumeration value="epr4m2ta1r1ac5"/>
                     <xsd:enumeration value="epr4m2ta1r1c1"/>
                     <xsd:enumeration value="epr4m2ta1r1c2"/>
                     <xsd:enumeration value="epr4m2ta1r1c3"/>
                     <xsd:enumeration value="epr4m2ta1r1c4"/>
                     <xsd:enumeration value="epr4m2ta1r1c5"/>
                     <xsd:enumeration value="epr4m2ta1r2ac1"/>
                     <xsd:enumeration value="epr4m2ta1r2ac2"/>
                     <xsd:enumeration value="epr4m2ta1r2ac3"/>
                     <xsd:enumeration value="epr4m2ta1r2ac4"/>
                     <xsd:enumeration value="epr4m2ta1r2ac5"/>
                     <xsd:enumeration value="epr4m2ta1r2cc1"/>
                     <xsd:enumeration value="epr4m2ta1r2cc2"/>
                     <xsd:enumeration value="epr4m2ta1r2cc3"/>
                     <xsd:enumeration value="epr4m2ta1r2cc4"/>
                     <xsd:enumeration value="epr4m2ta1r2cc5"/>
                     <xsd:enumeration value="epr4m2ta1r2bc1"/>
                     <xsd:enumeration value="epr4m2ta1r2bc2"/>
                     <xsd:enumeration value="epr4m2ta1r2bc3"/>
                     <xsd:enumeration value="epr4m2ta1r2bc4"/>
                     <xsd:enumeration value="epr4m2ta1r2bc5"/>
                     <xsd:enumeration value="epr4m2ta1r3c1"/>
                     <xsd:enumeration value="epr4m2ta1r3c2"/>
                     <xsd:enumeration value="epr4m2ta1r3c3"/>
                     <xsd:enumeration value="epr4m2ta1r3c4"/>
                     <xsd:enumeration value="epr4m2ta1r3c5"/>
                     <xsd:enumeration value="epr4m2ta1r4c1"/>
                     <xsd:enumeration value="epr4m2ta1r4c2"/>
                     <xsd:enumeration value="epr4m2ta1r4c3"/>
                     <xsd:enumeration value="epr4m2ta1r4c4"/>
                     <xsd:enumeration value="epr4m2ta1r4c5"/>
                     <xsd:enumeration value="epr4m2ta1r5c1"/>
                     <xsd:enumeration value="epr4m2ta1r5c2"/>
                     <xsd:enumeration value="epr4m2ta1r5c3"/>
                     <xsd:enumeration value="epr4m2ta1r5c4"/>
                     <xsd:enumeration value="epr4m2ta1r5c5"/>
                     <xsd:enumeration value="epr4m2ta1r6c1"/>
                     <xsd:enumeration value="epr4m2ta1r6c2"/>
                     <xsd:enumeration value="epr4m2ta1r6c3"/>
                     <xsd:enumeration value="epr4m2ta1r6c4"/>
                     <xsd:enumeration value="epr4m2ta1r6c5"/>
                     <xsd:enumeration value="epr4m2ta2r1ac1"/>
                     <xsd:enumeration value="epr4m2ta2r1ac2"/>
                     <xsd:enumeration value="epr4m2ta2r1bc1"/>
                     <xsd:enumeration value="epr4m2ta2r1bc2"/>
                     <xsd:enumeration value="epr4m2ta2r2c1"/>
                     <xsd:enumeration value="epr4m2ta2r2c2"/>
                     <xsd:enumeration value="epr4m2ta2r2c3"/>
                     <xsd:enumeration value="epr4m2ta2r2c4"/>
                     <xsd:enumeration value="epr4m2ta2r3c1"/>
                     <xsd:enumeration value="epr4m2ta2r3c2"/>
                     <xsd:enumeration value="epr4m2ta2r3c3"/>
                     <xsd:enumeration value="epr4m2ta2r3c4"/>
                     <xsd:enumeration value="epr4m2ta2r4ac1"/>
                     <xsd:enumeration value="epr4m2ta2r4ac2"/>
                     <xsd:enumeration value="epr4m2ta2r4ac3"/>
                     <xsd:enumeration value="epr4m2ta2r4ac4"/>
                     <xsd:enumeration value="epr4m2ta2r4bc1"/>
                     <xsd:enumeration value="epr4m2ta2r4bc2"/>
                     <xsd:enumeration value="epr4m2ta2r4bc3"/>
                     <xsd:enumeration value="epr4m2ta2r4bc4"/>
                     <xsd:enumeration value="epr4m2ta2r5c1"/>
                     <xsd:enumeration value="epr4m2ta2r5c2"/>
                     <xsd:enumeration value="epr4m2ta2r5c3"/>
                     <xsd:enumeration value="epr4m2ta2r5c4"/>
                     <xsd:enumeration value="epr4m2ta2r6c1"/>
                     <xsd:enumeration value="epr4m2ta2r6c2"/>
                     <xsd:enumeration value="epr4m2ta2r6c3"/>
                     <xsd:enumeration value="epr4m2ta2r6c4"/>
                     <xsd:enumeration value="epr4m2ta2r7c1"/>
                     <xsd:enumeration value="epr4m2ta2r7c2"/>
                     <xsd:enumeration value="epr4m2ta2r8c1"/>
                     <xsd:enumeration value="epr4m2ta2r8c2"/>
                     <xsd:enumeration value="epr4m2ta2r9c1"/>
                     <xsd:enumeration value="epr4m2ta2r9c2"/>
                     <xsd:enumeration value="epr4m2ta2r10c1"/>
                     <xsd:enumeration value="epr4m2ta2r10c2"/>
                     <xsd:enumeration value="epr4m2ta3r1c1"/>
                     <xsd:enumeration value="epr4m2ta3r1c2"/>
                     <xsd:enumeration value="epr4m2ta3r1c3"/>
                     <xsd:enumeration value="epr4m2ta3r1c4"/>
                     <xsd:enumeration value="epr4m2ta3r2c1"/>
                     <xsd:enumeration value="epr4m2ta3r2c2"/>
                     <xsd:enumeration value="epr4m2ta3r2c3"/>
                     <xsd:enumeration value="epr4m2ta3r2c4"/>
                     <xsd:enumeration value="epr4m2ta3r3c1"/>
                     <xsd:enumeration value="epr4m2ta3r3c2"/>
                     <xsd:enumeration value="epr4m2ta3r3c3"/>
                     <xsd:enumeration value="epr4m2ta3r3c4"/>
                     <xsd:enumeration value="epr4m2ta3r4c1"/>
                     <xsd:enumeration value="epr4m2ta3r4c2"/>
                     <xsd:enumeration value="epr4m2ta3r4c3"/>
                     <xsd:enumeration value="epr4m2ta3r4c4"/>
                     <xsd:enumeration value="epr4m2ta3r5c1"/>
                     <xsd:enumeration value="epr4m2ta3r5c2"/>
                     <xsd:enumeration value="epr4m2ta3r5c3"/>
                     <xsd:enumeration value="epr4m2ta3r5c4"/>
                     <xsd:enumeration value="epr4m2ta3r6c1"/>
                     <xsd:enumeration value="epr4m2ta3r6c2"/>
                     <xsd:enumeration value="epr4m2ta3r6c3"/>
                     <xsd:enumeration value="epr4m2ta3r6c4"/>
                     <xsd:enumeration value="epr4m2ta3r7c1"/>
                     <xsd:enumeration value="epr4m2ta3r7c2"/>
                     <xsd:enumeration value="epr4m2ta3r7c3"/>
                     <xsd:enumeration value="epr4m2ta3r7c4"/>
                     <xsd:enumeration value="epr4m2ta3r8c1"/>
                     <xsd:enumeration value="epr4m2ta3r8c2"/>
                     <xsd:enumeration value="epr4m2ta3r8c3"/>
                     <xsd:enumeration value="epr4m2ta3r8c4"/>
                     <xsd:enumeration value="epr4m2ta3r9c1"/>
                     <xsd:enumeration value="epr4m2ta3r9c2"/>
                     <xsd:enumeration value="epr4m2ta3r9c3"/>
                     <xsd:enumeration value="epr4m2ta3r9c4"/>
                     <xsd:enumeration value="epr4m2ta3r10c1"/>
                     <xsd:enumeration value="epr4m2ta3r10c2"/>
                     <xsd:enumeration value="epr4m2ta3r10c3"/>
                     <xsd:enumeration value="epr4m2ta3r10c4"/>
                     <xsd:enumeration value="epr4m2ta3r11c1"/>
                     <xsd:enumeration value="epr4m2ta3r11c2"/>
                     <xsd:enumeration value="epr4m2ta3r11c3"/>
                     <xsd:enumeration value="epr4m2ta3r11c4"/>
                     <xsd:enumeration value="epr4m2ta4r1c1"/>
                     <xsd:enumeration value="epr4m2ta4r1c2"/>
                     <xsd:enumeration value="epr4m2ta5r1c1"/>
                     <xsd:enumeration value="epr4m2ta5r1c2"/>
                     <xsd:enumeration value="epr4m2ta5r2c1"/>
                     <xsd:enumeration value="epr4m2ta5r2c2"/>
                     <xsd:enumeration value="epr4m2ta5r3c1"/>
                     <xsd:enumeration value="epr4m2ta5r3c2"/>
                     <xsd:enumeration value="epr4m2ta5r4c1"/>
                     <xsd:enumeration value="epr4m2ta5r4c2"/>
                     <xsd:enumeration value="epr4m2ta5r5c1"/>
                     <xsd:enumeration value="epr4m2ta5r5c3"/>
                     <xsd:enumeration value="epr4m2ta5r6c1"/>
                     <xsd:enumeration value="epr4m2ta5r6c3"/>
                     <xsd:enumeration value="epr4m2ta5r7c1"/>
                     <xsd:enumeration value="epr4m2ta5r7c2"/>
                     <xsd:enumeration value="epr4m2ta5r8c1"/>
                     <xsd:enumeration value="epr4m2ta5r8c2"/>
                     <xsd:enumeration value="epr4m2ta5r9c1"/>
                     <xsd:enumeration value="epr4m2ta5r9c3"/>
                     <xsd:enumeration value="epr4m2ta5r10c1"/>
                     <xsd:enumeration value="epr4m2ta5r10c3"/>
                     <xsd:enumeration value="epr4m2ta5r11c1"/>
                     <xsd:enumeration value="epr4m2ta5r11c3"/>
                     <xsd:enumeration value="epr4m2ta5r12c1"/>
                     <xsd:enumeration value="epr4m2ta5r12c2"/>
                     <xsd:enumeration value="epr4m2ta6r1c1"/>
                     <xsd:enumeration value="epr4m2ta6r1c3"/>
                     <xsd:enumeration value="epr4m2tb1r1c1"/>
                     <xsd:enumeration value="epr4m2tb1r1c2"/>
                     <xsd:enumeration value="epr4m2tb1r1bc1"/>
                     <xsd:enumeration value="epr4m2tb1r1bc2"/>
                     <xsd:enumeration value="epr4m2tb1r2c1"/>
                     <xsd:enumeration value="epr4m2tb1r2c2"/>
                     <xsd:enumeration value="epr4m2tb1r3c1"/>
                     <xsd:enumeration value="epr4m2tb1r3c2"/>
                     <xsd:enumeration value="epr4m2tb1r5c1"/>
                     <xsd:enumeration value="epr4m2tb1r5c2"/>
                     <xsd:enumeration value="epr4m2tb1r6c1"/>
                     <xsd:enumeration value="epr4m2tb1r6c2"/>
                     <xsd:enumeration value="epr4m2tb1r7c1"/>
                     <xsd:enumeration value="epr4m2tb1r7c2"/>
                     <xsd:enumeration value="epr4m2tb1r7c3"/>
                     <xsd:enumeration value="epr4m2tb1r7c4"/>
                     <xsd:enumeration value="epr4m2tb1r8c5"/>
                     <xsd:enumeration value="epr4m2tb1r8c1"/>
                     <xsd:enumeration value="epr4m2tb1r8c2"/>
                     <xsd:enumeration value="epr4m2tb1r9c1"/>
                     <xsd:enumeration value="epr4m2tb1r9c2"/>
                     <xsd:enumeration value="epr4m2tb1r10c1"/>
                     <xsd:enumeration value="epr4m2tb1r10c2"/>
                     <xsd:enumeration value="epr4m2tb1r14c1"/>
                     <xsd:enumeration value="epr4m2tb1r14c2"/>
                     <xsd:enumeration value="epr4m2tb1r14ac1"/>
                     <xsd:enumeration value="epr4m2tb1r14ac2"/>
                     <xsd:enumeration value="epr4m2tb1r14ac3"/>
                     <xsd:enumeration value="epr4m2tb1r14ac4"/>
                     <xsd:enumeration value="epr4m2tb1r15c1"/>
                     <xsd:enumeration value="epr4m2tb1r15c2"/>
                     <xsd:enumeration value="epr4m2tb1r16c1"/>
                     <xsd:enumeration value="epr4m2tb1r16c2"/>
                     <xsd:enumeration value="epr4m2tb2r1c1"/>
                     <xsd:enumeration value="epr4m2tb2r1c2"/>
                     <xsd:enumeration value="epr4m2tb2r1c3"/>
                     <xsd:enumeration value="epr4m2tb2r1c4"/>
                     <xsd:enumeration value="epr4m2tb2r2c1"/>
                     <xsd:enumeration value="epr4m2tb2r2c2"/>
                     <xsd:enumeration value="epr4m2tb2r2c3"/>
                     <xsd:enumeration value="epr4m2tb2r2c4"/>
                     <xsd:enumeration value="epr4m2tb2r3c1"/>
                     <xsd:enumeration value="epr4m2tb2r3c2"/>
                     <xsd:enumeration value="epr4m2tb2r3c3"/>
                     <xsd:enumeration value="epr4m2tb2r3c4"/>
                     <xsd:enumeration value="epr4m2tb2r4c1"/>
                     <xsd:enumeration value="epr4m2tb2r4c2"/>
                     <xsd:enumeration value="epr4m2tb2r4c3"/>
                     <xsd:enumeration value="epr4m2tb2r4c4"/>
                     <xsd:enumeration value="epr4m2tb2r5c1"/>
                     <xsd:enumeration value="epr4m2tb2r5c2"/>
                     <xsd:enumeration value="epr4m2tb2r5c3"/>
                     <xsd:enumeration value="epr4m2tb2r5c4"/>
                     <xsd:enumeration value="epr4m2tb2r6c1"/>
                     <xsd:enumeration value="epr4m2tb2r6c2"/>
                     <xsd:enumeration value="epr4m2tb2r6c3"/>
                     <xsd:enumeration value="epr4m2tb2r6c4"/>
                     <xsd:enumeration value="epr4m2tb2r7c1"/>
                     <xsd:enumeration value="epr4m2tb2r7c2"/>
                     <xsd:enumeration value="epr4m2tb2r7c3"/>
                     <xsd:enumeration value="epr4m2tb2r7c4"/>
                     <xsd:enumeration value="epr4m2tb2r8c1"/>
                     <xsd:enumeration value="epr4m2tb2r8c2"/>
                     <xsd:enumeration value="epr4m2tb2r8c3"/>
                     <xsd:enumeration value="epr4m2tb2r8c4"/>
                     <xsd:enumeration value="epr4m2tb2r8bc1"/>
                     <xsd:enumeration value="epr4m2tb2r8bc2"/>
                     <xsd:enumeration value="epr4m2tb2r8bc3"/>
                     <xsd:enumeration value="epr4m2tb2r8bc4"/>
                     <xsd:enumeration value="epr4m2tb2r9bc1"/>
                     <xsd:enumeration value="epr4m2tb2r9bc2"/>
                     <xsd:enumeration value="epr4m2tb2r9bc3"/>
                     <xsd:enumeration value="epr4m2tb2r9bc4"/>
                     <xsd:enumeration value="epr4m2tb2r9c1"/>
                     <xsd:enumeration value="epr4m2tb2r9c2"/>
                     <xsd:enumeration value="epr4m2tb2r9c3"/>
                     <xsd:enumeration value="epr4m2tb2r9c4"/>
                     <xsd:enumeration value="epr4m2tb2r9ac1"/>
                     <xsd:enumeration value="epr4m2tb2r9ac2"/>
                     <xsd:enumeration value="epr4m2tb2r9ac3"/>
                     <xsd:enumeration value="epr4m2tb2r9ac4"/>
                     <xsd:enumeration value="epr4m2tb2r10c1"/>
                     <xsd:enumeration value="epr4m2tb2r10c2"/>
                     <xsd:enumeration value="epr4m2tb2r10c3"/>
                     <xsd:enumeration value="epr4m2tb2r10c4"/>
                     <xsd:enumeration value="epr4m2tb2r11c1"/>
                     <xsd:enumeration value="epr4m2tb2r11c2"/>
                     <xsd:enumeration value="epr4m2tb2r12c1"/>
                     <xsd:enumeration value="epr4m2tb2r12c2"/>
                     <xsd:enumeration value="epr4m2tb2r13c1"/>
                     <xsd:enumeration value="epr4m2tb2r13c2"/>
                     <xsd:enumeration value="epr4m2tb2r14c1"/>
                     <xsd:enumeration value="epr4m2tb2r14c2"/>
                     <xsd:enumeration value="epr4m2tb2r15c1"/>
                     <xsd:enumeration value="epr4m2tb2r15c2"/>
                     <xsd:enumeration value="epr4m2tb2r16c1"/>
                     <xsd:enumeration value="epr4m2tb2r16c2"/>
                     <xsd:enumeration value="epr4m2tb2r17c1"/>
                     <xsd:enumeration value="epr4m2tb2r17c2"/>
                     <xsd:enumeration value="epr4m2tb2r18c1"/>
                     <xsd:enumeration value="epr4m2tb2r18c2"/>
                     <xsd:enumeration value="epr4m2tb2r19c1"/>
                     <xsd:enumeration value="epr4m2tb2r19c2"/>
                     <xsd:enumeration value="epr4m2tb3r1c1"/>
                     <xsd:enumeration value="epr4m2tb3r1c2"/>
                     <xsd:enumeration value="epr4m2tb3r3c6"/>
                     <xsd:enumeration value="epr4m2tb3r3c7"/>
                     <xsd:enumeration value="epr4m2tb3r2c1"/>
                     <xsd:enumeration value="epr4m2tb3r2c2"/>
                     <xsd:enumeration value="epr4m2tb3r2c3"/>
                     <xsd:enumeration value="epr4m2tb3r2c3a"/>
                     <xsd:enumeration value="epr4m2tb3r2c4"/>
                     <xsd:enumeration value="epr4m2tb3r2c4a"/>
                     <xsd:enumeration value="epr4m2tb3r2c5"/>
                     <xsd:enumeration value="epr4m2tb4r1c4"/>
                     <xsd:enumeration value="epr4m2tb4r1c5"/>
                     <xsd:enumeration value="epr4m2tb5r1c1"/>
                     <xsd:enumeration value="epr4m2tb5r1c2"/>
                     <xsd:enumeration value="epr4m2tb5r3c1"/>
                     <xsd:enumeration value="epr4m2tb5r3c2"/>
                     <xsd:enumeration value="epr4m2tb5r3ac1"/>
                     <xsd:enumeration value="epr4m2tb5r3ac2"/>
                     <xsd:enumeration value="epr4m2tb5r4c1"/>
                     <xsd:enumeration value="epr4m2tb5r4c2"/>
                     <xsd:enumeration value="epr4m2tb6r1c1"/>
                     <xsd:enumeration value="epr4m2tb6r1c2"/>
                     <xsd:enumeration value="epr4m2tb7r1c1"/>
                     <xsd:enumeration value="epr4m2tb7r1c2"/>
                     <xsd:enumeration value="epr4m2tb7r3c1"/>
                     <xsd:enumeration value="epr4m2tb7r3c2"/>
                     <xsd:enumeration value="epr4m2tb8r1c1"/>
                     <xsd:enumeration value="epr4m2tb8r1c3"/>
                     <xsd:enumeration value="epr4m2tb8r1ac1"/>
                     <xsd:enumeration value="epr4m2tb8r1ac2"/>
                     <xsd:enumeration value="epr4m2tb8r2c1"/>
                     <xsd:enumeration value="epr4m2tb8r2c2"/>
                     <xsd:enumeration value="epr4m2tb8r4c1"/>
                     <xsd:enumeration value="epr4m2tb8r4c3"/>
                     <xsd:enumeration value="epr4m2tb8r6c1"/>
                     <xsd:enumeration value="epr4m2tb8r6c2"/>
                     <xsd:enumeration value="epr4m2tc1r1c1"/>
                     <xsd:enumeration value="epr4m2tc1r1c2"/>
                     <xsd:enumeration value="epr4m2tc1r2c1"/>
                     <xsd:enumeration value="epr4m2tc1r2c2"/>
                     <xsd:enumeration value="epr4m2tc1r3c1"/>
                     <xsd:enumeration value="epr4m2tc1r3c2"/>
                     <xsd:enumeration value="epr4m2tc1r4c1"/>
                     <xsd:enumeration value="epr4m2tc1r4c2"/>
                     <xsd:enumeration value="epr4m2tc1r4ac1"/>
                     <xsd:enumeration value="epr4m2tc1r5c1"/>
                     <xsd:enumeration value="epr4m2tc1r5c2"/>
                     <xsd:enumeration value="epr4m2tc1r6c1"/>
                     <xsd:enumeration value="epr4m2tc1r6c2"/>
                     <xsd:enumeration value="epr4m2tc1r7c1"/>
                     <xsd:enumeration value="epr4m2tc1r7c2"/>
                     <xsd:enumeration value="epr4m2tc1r8c1"/>
                     <xsd:enumeration value="epr4m2tc1r8c2"/>
                     <xsd:enumeration value="epr4m2tc2r1c1"/>
                     <xsd:enumeration value="epr4m2tc2r1c2"/>
                     <xsd:enumeration value="epr4m2tc2r2c1"/>
                     <xsd:enumeration value="epr4m2tc2r2c2"/>
                     <xsd:enumeration value="epr4m2tc2r3c1"/>
                     <xsd:enumeration value="epr4m2tc2r3c2"/>
                     <xsd:enumeration value="epr4m2tc2r4c1"/>
                     <xsd:enumeration value="epr4m2tc2r4c2"/>
                     <xsd:enumeration value="epr4m2tc2r5c1"/>
                     <xsd:enumeration value="epr4m2tc2r5c2"/>
                     <xsd:enumeration value="epr4m2tc2r6c1"/>
                     <xsd:enumeration value="epr4m2tc2r6c2"/>
                     <xsd:enumeration value="epr4m2tc3r1c1"/>
                     <xsd:enumeration value="epr4m2tc3r2c1"/>
                     <xsd:enumeration value="epr4m2tc3r3c1"/>
                     <xsd:enumeration value="epr4m2tc3r4c1"/>
                     <xsd:enumeration value="epr4m2tc4r1c1"/>
                     <xsd:enumeration value="epr4m2tc4r1c2"/>
                     <xsd:enumeration value="epr4m2tc4r1c3"/>
                     <xsd:enumeration value="epr4m2tc4r1c4"/>
                     <xsd:enumeration value="epr4m2tc4r1c5"/>
                     <xsd:enumeration value="epr4m2tc4r1c6"/>
                     <xsd:enumeration value="epr4m2tc4r1c7"/>
                     <xsd:enumeration value="epr4m2tc4r1c8"/>
                     <xsd:enumeration value="epr4m2tc4r5c1"/>
                     <xsd:enumeration value="epr4m2tc4r5c2"/>
                     <xsd:enumeration value="epr4m2tc4r5c3"/>
                     <xsd:enumeration value="epr4m2tc4r5c4"/>
                     <xsd:enumeration value="epr4m2tc4r5c5"/>
                     <xsd:enumeration value="epr4m2tc4r5c6"/>
                     <xsd:enumeration value="epr4m2tc4r5c7"/>
                     <xsd:enumeration value="epr4m2tc4r5c8"/>
                     <xsd:enumeration value="epr4m2tc4r6c1"/>
                     <xsd:enumeration value="epr4m2tc4r6c2"/>
                     <xsd:enumeration value="epr4m2tc4r6c3"/>
                     <xsd:enumeration value="epr4m2tc4r6c4"/>
                     <xsd:enumeration value="epr4m2tc4r6c5"/>
                     <xsd:enumeration value="epr4m2tc4r6c6"/>
                     <xsd:enumeration value="epr4m2tc4r6c7"/>
                     <xsd:enumeration value="epr4m2tc4r6c8"/>
                     <xsd:enumeration value="epr4m2tc4r7c1"/>
                     <xsd:enumeration value="epr4m2tc4r7c2"/>
                     <xsd:enumeration value="epr4m2tc4r7c3"/>
                     <xsd:enumeration value="epr4m2tc5r1c1"/>
                     <xsd:enumeration value="epr4m2tc5r1c2"/>
                     <xsd:enumeration value="epr4m2tc5r1c3"/>
                     <xsd:enumeration value="epr4m2tc5r1c4"/>
                     <xsd:enumeration value="epr4m2tc5r1c5"/>
                     <xsd:enumeration value="epr4m2tc5r1c6"/>
                     <xsd:enumeration value="epr4m2tc5r1c7"/>
                     <xsd:enumeration value="epr4m2tc5r1c8"/>
                     <xsd:enumeration value="epr4m2tc5r5c1"/>
                     <xsd:enumeration value="epr4m2tc5r5c2"/>
                     <xsd:enumeration value="epr4m2tc5r5c3"/>
                     <xsd:enumeration value="epr4m2tc5r5c4"/>
                     <xsd:enumeration value="epr4m2tc5r5c5"/>
                     <xsd:enumeration value="epr4m2tc5r5c6"/>
                     <xsd:enumeration value="epr4m2tc5r5c7"/>
                     <xsd:enumeration value="epr4m2tc5r5c8"/>
                     <xsd:enumeration value="epr4m2tc5r6c1"/>
                     <xsd:enumeration value="epr4m2tc5r6c2"/>
                     <xsd:enumeration value="epr4m2tc5r6c3"/>
                     <xsd:enumeration value="epr4m2tc5r6c4"/>
                     <xsd:enumeration value="epr4m2tc5r6c5"/>
                     <xsd:enumeration value="epr4m2tc5r6c6"/>
                     <xsd:enumeration value="epr4m2tc5r6c7"/>
                     <xsd:enumeration value="epr4m2tc5r6c8"/>
                     <xsd:enumeration value="epr4m2tc5r7c1"/>
                     <xsd:enumeration value="epr4m2tc5r7c2"/>
                     <xsd:enumeration value="epr4m2tc5r7c3"/>
                     <xsd:enumeration value="epr4m2tc6r1c1"/>
                     <xsd:enumeration value="epr4m2tc6r1c2"/>
                     <xsd:enumeration value="epr4m2tc6r1c3"/>
                     <xsd:enumeration value="epr4m2tc6r1c4"/>
                     <xsd:enumeration value="epr4m2tc6r1c5"/>
                     <xsd:enumeration value="epr4m2tc6r1c6"/>
                     <xsd:enumeration value="epr4m2tc6r1c7"/>
                     <xsd:enumeration value="epr4m2tc6r1c8"/>
                     <xsd:enumeration value="epr4m2tc6r4c1"/>
                     <xsd:enumeration value="epr4m2tc6r4c2"/>
                     <xsd:enumeration value="epr4m2tc6r4c3"/>
                     <xsd:enumeration value="epr4m2tc6r4c4"/>
                     <xsd:enumeration value="epr4m2tc6r4c5"/>
                     <xsd:enumeration value="epr4m2tc6r4c6"/>
                     <xsd:enumeration value="epr4m2tc6r4c7"/>
                     <xsd:enumeration value="epr4m2tc6r4c8"/>
                     <xsd:enumeration value="epr4m2tc6r5c1"/>
                     <xsd:enumeration value="epr4m2tc6r5c2"/>
                     <xsd:enumeration value="epr4m2tc6r5c3"/>
                     <xsd:enumeration value="epr4m2tc6r5c4"/>
                     <xsd:enumeration value="epr4m2tc6r5c5"/>
                     <xsd:enumeration value="epr4m2tc6r5c6"/>
                     <xsd:enumeration value="epr4m2tc6r5c7"/>
                     <xsd:enumeration value="epr4m2tc6r5c8"/>
                     <xsd:enumeration value="epr4m2tc6r6c1"/>
                     <xsd:enumeration value="epr4m2tc6r6c2"/>
                     <xsd:enumeration value="epr4m2tc6r6c3"/>
                     <xsd:enumeration value="epr4m2tc7r1c1"/>
                     <xsd:enumeration value="epr4m2tc7r1c2"/>
                     <xsd:enumeration value="epr4m2tc7r1c3"/>
                     <xsd:enumeration value="epr4m2tc7r1c4"/>
                     <xsd:enumeration value="epr4m2tc7r1c5"/>
                     <xsd:enumeration value="epr4m2tc7r1c6"/>
                     <xsd:enumeration value="epr4m2tc7r1c7"/>
                     <xsd:enumeration value="epr4m2tc7r1c8"/>
                     <xsd:enumeration value="epr4m2tc7r5c1"/>
                     <xsd:enumeration value="epr4m2tc7r5c2"/>
                     <xsd:enumeration value="epr4m2tc7r5c3"/>
                     <xsd:enumeration value="epr4m2tc7r5c4"/>
                     <xsd:enumeration value="epr4m2tc7r5c5"/>
                     <xsd:enumeration value="epr4m2tc7r5c6"/>
                     <xsd:enumeration value="epr4m2tc7r5c7"/>
                     <xsd:enumeration value="epr4m2tc7r5c8"/>
                     <xsd:enumeration value="epr4m2tc7r6c1"/>
                     <xsd:enumeration value="epr4m2tc7r6c2"/>
                     <xsd:enumeration value="epr4m2tc7r6c3"/>
                     <xsd:enumeration value="epr4m2tc7r6c4"/>
                     <xsd:enumeration value="epr4m2tc7r6c5"/>
                     <xsd:enumeration value="epr4m2tc7r6c6"/>
                     <xsd:enumeration value="epr4m2tc7r6c7"/>
                     <xsd:enumeration value="epr4m2tc7r6c8"/>
                     <xsd:enumeration value="epr4m2tc7r7c1"/>
                     <xsd:enumeration value="epr4m2tc7r7c2"/>
                     <xsd:enumeration value="epr4m2tc7r7c3"/>
                     <xsd:enumeration value="epr4m2tc7r9c4"/>
                     <xsd:enumeration value="epr4m2tc7r9c5"/>
                     <xsd:enumeration value="epr4m2tc7r9c6"/>
                     <xsd:enumeration value="epr4m2tc8r1c1"/>
                     <xsd:enumeration value="epr4m2tc8r1c2"/>
                     <xsd:enumeration value="epr4m2tc9r1c1"/>
                     <xsd:enumeration value="epr4m2tc9r1c2"/>
                     <xsd:enumeration value="epr4m2tc9r1c3"/>
                     <xsd:enumeration value="epr4m2tc9r1c4"/>
                     <xsd:enumeration value="epr4m2tc9r2c1"/>
                     <xsd:enumeration value="epr4m2tc9r2c2"/>
                     <xsd:enumeration value="epr4m2tc9r2c3"/>
                     <xsd:enumeration value="epr4m2tc9r2c4"/>
                     <xsd:enumeration value="epr4m2tc9r3c1"/>
                     <xsd:enumeration value="epr4m2tc9r3c2"/>
                     <xsd:enumeration value="epr4m2tc9r3bc1"/>
                     <xsd:enumeration value="epr4m2tc9r3bc2"/>
                     <xsd:enumeration value="epr4m2tc9r4c1"/>
                     <xsd:enumeration value="epr4m2tc9r4c2"/>
                     <xsd:enumeration value="epr4m2tc9r4bc1"/>
                     <xsd:enumeration value="epr4m2tc9r4bc2"/>
                     <xsd:enumeration value="epr4m2tc9r5c1"/>
                     <xsd:enumeration value="epr4m2tc9r5c2"/>
                     <xsd:enumeration value="epr4m2tc9r5ac1"/>
                     <xsd:enumeration value="epr4m2tc9r5ac2"/>
                     <xsd:enumeration value="epr4m2tc9r5ac3"/>
                     <xsd:enumeration value="epr4m2tc9r5ac4"/>
                     <xsd:enumeration value="epr4m2tc9r6c1"/>
                     <xsd:enumeration value="epr4m2tc9r6c2"/>
                     <xsd:enumeration value="epr4m2tc9r6c3"/>
                     <xsd:enumeration value="epr4m2tc9r6c4"/>
                     <xsd:enumeration value="epr4m2tc9r7c1"/>
                     <xsd:enumeration value="epr4m2tc9r7c2"/>
                     <xsd:enumeration value="epr4m2tc9r8ac1"/>
                     <xsd:enumeration value="epr4m2tc9r8ac2"/>
                     <xsd:enumeration value="epr4m2tc9r8ac3"/>
                     <xsd:enumeration value="epr4m2tc9r8ac4"/>
                     <xsd:enumeration value="epr4m2tc9r8bc3"/>
                     <xsd:enumeration value="epr4m2tc9r8bc4"/>
                     <xsd:enumeration value="epr4m2tc9r8c1"/>
                     <xsd:enumeration value="epr4m2tc9r8c2"/>
                     <xsd:enumeration value="epr4m2tc9r8c3"/>
                     <xsd:enumeration value="epr4m2tc9r8c4"/>
                     <xsd:enumeration value="epr4m2tc9r9c1"/>
                     <xsd:enumeration value="epr4m2tc9r9c2"/>
                     <xsd:enumeration value="epr4m2tc9r9c3"/>
                     <xsd:enumeration value="epr4m2tc9r9c4"/>
                     <xsd:enumeration value="epr4m2tc12r1c1"/>
                     <xsd:enumeration value="epr4m2tc12r1c2"/>
                     <xsd:enumeration value="epr4m2tc12r1c3"/>
                     <xsd:enumeration value="epr4m2tc12r1c4"/>
                     <xsd:enumeration value="epr4m2tc12r2c1"/>
                     <xsd:enumeration value="epr4m2tc12r2c2"/>
                     <xsd:enumeration value="epr4m2tc12r2c3"/>
                     <xsd:enumeration value="epr4m2tc12r2c4"/>
                     <xsd:enumeration value="epr4m2tc12r3ac1"/>
                     <xsd:enumeration value="epr4m2tc12r3ac2"/>
                     <xsd:enumeration value="epr4m2tc12r3ac3"/>
                     <xsd:enumeration value="epr4m2tc12r3ac4"/>
                     <xsd:enumeration value="epr4m2tc12r3c1"/>
                     <xsd:enumeration value="epr4m2tc12r3c2"/>
                     <xsd:enumeration value="epr4m2tc12r3c3"/>
                     <xsd:enumeration value="epr4m2tc12r3c4"/>
                     <xsd:enumeration value="epr4m2tc12r4c1"/>
                     <xsd:enumeration value="epr4m2tc12r4c2"/>
                     <xsd:enumeration value="epr4m2tc12r4c3"/>
                     <xsd:enumeration value="epr4m2tc12r4c4"/>
                     <xsd:enumeration value="epr4m2tc12r5c1"/>
                     <xsd:enumeration value="epr4m2tc12r5c2"/>
                     <xsd:enumeration value="epr4m2tc12r5c3"/>
                     <xsd:enumeration value="epr4m2tc12r5c4"/>
                     <xsd:enumeration value="epr4m2tc12r6c1"/>
                     <xsd:enumeration value="epr4m2tc12r6c2"/>
                     <xsd:enumeration value="epr4m2tc12r6c3"/>
                     <xsd:enumeration value="epr4m2tc12r6c4"/>
                     <xsd:enumeration value="epr4m2tc12r7c1"/>
                     <xsd:enumeration value="epr4m2tc12r7c2"/>
                     <xsd:enumeration value="epr4m2tc12r7c3"/>
                     <xsd:enumeration value="epr4m2tc12r7c4"/>
                     <xsd:enumeration value="epr4m2tc12r8c1"/>
                     <xsd:enumeration value="epr4m2tc12r8c2"/>
                     <xsd:enumeration value="epr4m2tc12r8c3"/>
                     <xsd:enumeration value="epr4m2tc12r8c4"/>
                     <xsd:enumeration value="epr4m2tc12r9c1"/>
                     <xsd:enumeration value="epr4m2tc12r9c2"/>
                     <xsd:enumeration value="epr4m2tc12r9c3"/>
                     <xsd:enumeration value="epr4m2tc12r9c4"/>
                     <xsd:enumeration value="epr4m2tc12r10c1"/>
                     <xsd:enumeration value="epr4m2tc12r10c2"/>
                     <xsd:enumeration value="epr4m2tc12r10c3"/>
                     <xsd:enumeration value="epr4m2tc12r10c4"/>
                     <xsd:enumeration value="epr4m2tc12r10bc1"/>
                     <xsd:enumeration value="epr4m2tc12r10bc2"/>
                     <xsd:enumeration value="epr4m2tc12r10bc3"/>
                     <xsd:enumeration value="epr4m2tc12r10bc4"/>
                     <xsd:enumeration value="epr4m2tc12r10dc1"/>
                     <xsd:enumeration value="epr4m2tc12r10dc2"/>
                     <xsd:enumeration value="epr4m2tc12r10dc3"/>
                     <xsd:enumeration value="epr4m2tc12r10dc4"/>
                     <xsd:enumeration value="epr4m2tc12r10cc1"/>
                     <xsd:enumeration value="epr4m2tc12r10cc2"/>
                     <xsd:enumeration value="epr4m2tc12r10cc3"/>
                     <xsd:enumeration value="epr4m2tc12r10cc4"/>
                     <xsd:enumeration value="epr4m2tc12r11c1"/>
                     <xsd:enumeration value="epr4m2tc12r12c1"/>
                     <xsd:enumeration value="epr4m2tc12r13c1"/>
                     <xsd:enumeration value="epr4m2tc13r1c1"/>
                     <xsd:enumeration value="epr4m2tc13r1c3"/>
                     <xsd:enumeration value="epr4m2tc13r1c4"/>
                     <xsd:enumeration value="epr4m2tc13r1ac1"/>
                     <xsd:enumeration value="epr4m2tc13r1ac3"/>
                     <xsd:enumeration value="epr4m2tc13r1ac4"/>
                     <xsd:enumeration value="epr4m2tc13r2c1"/>
                     <xsd:enumeration value="epr4m2tc13r2c3"/>
                     <xsd:enumeration value="epr4m2tc13r2c4"/>
                     <xsd:enumeration value="epr4m2tc13r3c1"/>
                     <xsd:enumeration value="epr4m2tc13r3c3"/>
                     <xsd:enumeration value="epr4m2tc13r3c4"/>
                     <xsd:enumeration value="epr4m2tc13r4c1"/>
                     <xsd:enumeration value="epr4m2tc13r4c3"/>
                     <xsd:enumeration value="epr4m2tc13r4c4"/>
                     <xsd:enumeration value="epr4m2tc14r2c5"/>
                     <xsd:enumeration value="epr4m2tc14r3c5"/>
                     <xsd:enumeration value="epr4m2tc14r4c5"/>
                     <xsd:enumeration value="epr4m2tc14r4c7"/>
                     <xsd:enumeration value="epr4m2tc14r4c8"/>
                     <xsd:enumeration value="epr4m2tc14r4c9"/>
                     <xsd:enumeration value="epr4m2tc14r5c1"/>
                     <xsd:enumeration value="epr4m2tc15r1c1"/>
                     <xsd:enumeration value="epr4m2tc15r2c1"/>
                     <xsd:enumeration value="epr4m2tc15r2c2"/>
                     <xsd:enumeration value="epr4m2tc15r2c3"/>
                     <xsd:enumeration value="epr4m2tc15r3c1"/>
                     <xsd:enumeration value="epr4m2tc15r4c1"/>
                     <xsd:enumeration value="epr4m2tc16r1c1"/>
                     <xsd:enumeration value="epr4m2tc16r2c1"/>
                     <xsd:enumeration value="epr4m2tc16r5c1"/>
                     <xsd:enumeration value="epr4m2tc16r6c1"/>
                     <xsd:enumeration value="epr4m2tc16r6c2"/>
                     <xsd:enumeration value="epr4m2tc16r7c1"/>
                     <xsd:enumeration value="epr4m2tc16r7c2"/>
                     <xsd:enumeration value="epr4m2tc16r7c3"/>
                     <xsd:enumeration value="epr4m2tc16r4c1"/>
					 <xsd:enumeration value="epr4m2tc16r4c2"/>
                     <xsd:enumeration value="epr4m2tc17r1c1"/>
                     <xsd:enumeration value="epr4m2tc17r1c2"/>
                     <xsd:enumeration value="epr4m2tc17r2c1"/>
                     <xsd:enumeration value="epr4m2tc17r2c2"/>
                     <xsd:enumeration value="epr4m2tc18r1c1"/>
                     <xsd:enumeration value="epr4m2tc18r2c1"/>
                     <xsd:enumeration value="epr4m2tc18r3c1"/>
                     <xsd:enumeration value="epr4m2tc18r4c1"/>
                     <xsd:enumeration value="epr4m2tc18r5c1"/>
                     <xsd:enumeration value="epr4m2tc18r6c1"/>
                     <xsd:enumeration value="epr4m2tc18r7c1"/>
                     <xsd:enumeration value="epr4m2tc18r7c2"/>
                     <xsd:enumeration value="epr4m2tc18r7c3"/>
                     <xsd:enumeration value="epr4m2tc19r1c1"/>
                     <xsd:enumeration value="epr4m2tc19r1c2"/>
                     <xsd:enumeration value="epr4m2tc19r2c1"/>
                     <xsd:enumeration value="epr4m2tc19r2c2"/>
                     <xsd:enumeration value="epr4m2tc19r3c1"/>
                     <xsd:enumeration value="epr4m2tc19r3c2"/>
                     <xsd:enumeration value="epr4m2tc19r4c1"/>
                     <xsd:enumeration value="epr4m2tc19r4c2"/>
                     <xsd:enumeration value="epr4m2tc19r5c1"/>
                     <xsd:enumeration value="epr4m2tc19r5c2"/>
                     <xsd:enumeration value="epr4m2tc19r5ac1"/>
                     <xsd:enumeration value="epr4m2tc19r5ac2"/>
                     <xsd:enumeration value="epr4m2tc19r6c1"/>
                     <xsd:enumeration value="epr4m2tc19r6c2"/>
                     <xsd:enumeration value="epr4m2tc20r2c3"/>
                     <xsd:enumeration value="epr4m2tc20r2c4"/>
                     <xsd:enumeration value="epr4m2tc20r2c5"/>
                     <xsd:enumeration value="epr4m2tc20r2c6"/>
                     <xsd:enumeration value="epr4m2tc20br2c4"/>
                     <xsd:enumeration value="epr4m2tc20br2c9"/>
                     <xsd:enumeration value="epr4m2tc21r1c1"/>
                     <xsd:enumeration value="epr4m2tc21r1c2"/>
                     <xsd:enumeration value="epr4m2tc21r1c3"/>
                     <xsd:enumeration value="epr4m2tc21r2c1"/>
                     <xsd:enumeration value="epr4m2tc21r2c2"/>
                     <xsd:enumeration value="epr4m2tc21r2c3"/>
                     <xsd:enumeration value="epr4m2tc22r1c1"/>
                     <xsd:enumeration value="epr4m2tc22r1c2"/>
                     <xsd:enumeration value="epr4m2tc22r1c3"/>
                     <xsd:enumeration value="epr4m2tc22r2c1"/>
                     <xsd:enumeration value="epr4m2tc22r2c2"/>
                     <xsd:enumeration value="epr4m2tc22r2c3"/>
                     <xsd:enumeration value="epr4m2tc22r3c1"/>
                     <xsd:enumeration value="epr4m2tc22r3c2"/>
                     <xsd:enumeration value="epr4m2tc22r3c3"/>
                     <xsd:enumeration value="epr4m2tc22r4c1"/>
                     <xsd:enumeration value="epr4m2tc22r4c2"/>
                     <xsd:enumeration value="epr4m2tc22r4c3"/>
                     <xsd:enumeration value="epr4m2tc22r5c1"/>
                     <xsd:enumeration value="epr4m2tc22r5c2"/>
                     <xsd:enumeration value="epr4m2tc22r5c3"/>
                     <xsd:enumeration value="epr4m2tc22r6c1"/>
                     <xsd:enumeration value="epr4m2tc22r6c2"/>
                     <xsd:enumeration value="epr4m2tc22r6c3"/>
                     <xsd:enumeration value="epr4m2tc22r7c1"/>
                     <xsd:enumeration value="epr4m2tc22r8c1"/>
                     <xsd:enumeration value="epr4m2tc22r8c2"/>
                     <xsd:enumeration value="epr4m2tc22r8c3"/>
                     <xsd:enumeration value="epr4m2tc22r9c1"/>
                     <xsd:enumeration value="epr4m2tc22r9c2"/>
                     <xsd:enumeration value="epr4m2tc22r9c3"/>
                     <xsd:enumeration value="epr4m3tar1c1"/>
                     <xsd:enumeration value="epr4m3tbr1c1"/>
                     <xsd:enumeration value="epr4m3tbr1c2"/>
                     <xsd:enumeration value="epr4m3tbr2c1"/>
                     <xsd:enumeration value="epr4m3tbr2c2"/>
                     <xsd:enumeration value="epr4m3tbr3c1"/>
                     <xsd:enumeration value="epr4m3tbr3c2"/>
                     <xsd:enumeration value="epr4m3tbr4c1"/>
                     <xsd:enumeration value="epr4m3tbr4c2"/>
                     <xsd:enumeration value="epr4m3tbr4bc1"/>
                     <xsd:enumeration value="epr4m3tbr4bc2"/>
                     <xsd:enumeration value="epr4m3tbr5c1"/>
                     <xsd:enumeration value="epr4m3tbr5c2"/>
                     <xsd:enumeration value="epr4m3tbr5ac2"/>
                     <xsd:enumeration value="epr4m3tbr5bc2"/>
                     <xsd:enumeration value="epr4m3tbr6c1"/>
                     <xsd:enumeration value="epr4m3tbr6c2"/>
                     <xsd:enumeration value="epr4m3tbr7c1"/>
                     <xsd:enumeration value="epr4m3tbr7c2"/>
                     <xsd:enumeration value="epr4m3tcr1c1"/>
                     <xsd:enumeration value="epr4m3tcr1c2"/>
                     <xsd:enumeration value="epr4m3tcr1bc1"/>
                     <xsd:enumeration value="epr4m3tcr1bc2"/>
                     <xsd:enumeration value="epr4m3tcr2c1"/>
                     <xsd:enumeration value="epr4m3tcr2c2"/>
                     <xsd:enumeration value="epr4m3tcr3c1"/>
                     <xsd:enumeration value="epr4m3tcr3c2"/>
                     <xsd:enumeration value="epr4m3tdr1c1"/>
                     <xsd:enumeration value="epr4m3tdr2c1"/>
                     <xsd:enumeration value="epr4m3tdr3c1"/>
                     <xsd:enumeration value="epr4m3tdr3c2"/>
                     <xsd:enumeration value="epr4m3tdr4c1"/>
                     <xsd:enumeration value="epr4m3tdr4c2"/>
                     <xsd:enumeration value="epr4m3tdr5c1"/>
                     <xsd:enumeration value="epr4m3tdr5c2"/>
                     <xsd:enumeration value="epr4m3tdr6c1"/>
                     <xsd:enumeration value="epr4m3tdr6c2"/>
                     <xsd:enumeration value="epr4m3tdr9c1"/>
                     <xsd:enumeration value="epr4m3tdr9c2"/>
                     <xsd:enumeration value="epr4m3tdr10c1"/>
                     <xsd:enumeration value="epr4m3tdr10c2"/>
                     <xsd:enumeration value="epr4m3tdr11c1"/>
                     <xsd:enumeration value="epr4m3tdr11c2"/>
                     <xsd:enumeration value="epr4m3ter1c1"/>
                     <xsd:enumeration value="epr4m3ter1c2"/>
                     <xsd:enumeration value="epr4m3ter3c1"/>
                     <xsd:enumeration value="epr4m3ter3c2"/>
                     <xsd:enumeration value="epr4m3ter4c1"/>
                     <xsd:enumeration value="epr4m3ter4c2"/>
                     <xsd:enumeration value="epr4m3ter5c1"/>
                     <xsd:enumeration value="epr4m3ter6c1"/>
                     <xsd:enumeration value="epr4m3ter6bc1"/>
                     <xsd:enumeration value="epr4m3ter6bc2"/>
                     <xsd:enumeration value="epr4m3ter7c1"/>
                     <xsd:enumeration value="epr4m3ter8c1"/>
                     <xsd:enumeration value="epr4m3ter8bc1"/>
                     <xsd:enumeration value="epr4m3ter9c1"/>
                     <xsd:enumeration value="epr4m3ter10c1"/>
                     <xsd:enumeration value="epr4m3ter11c1"/>
                     <xsd:enumeration value="epr4m3ter12c1"/>
                     <xsd:enumeration value="epr4m3ter13c1"/>
                     <xsd:enumeration value="epr4m3ter13c2"/>
                     <xsd:enumeration value="epr4m3tzr1ac1"/>
                     <xsd:enumeration value="epr4m3tzr1bc2"/>
                     <xsd:enumeration value="epr4m3tzr1bc3"/>
                     <xsd:enumeration value="epr4m3tzr1cc2"/>
                     <xsd:enumeration value="epr4m3tzr1dc2"/>
                     <xsd:enumeration value="epr4m3tzr1dc3"/>
                     <xsd:enumeration value="epr4m3tzr1c1"/>
                     <xsd:enumeration value="epr4m3tzr1c2"/>
                     <xsd:enumeration value="epr4m3tzr1c3"/>
                     <xsd:enumeration value="epr4m3tzr2c1"/>
                     <xsd:enumeration value="epr4m3tzr2c2"/>
                     <xsd:enumeration value="epr4m3tzr2c3"/>
                     <xsd:enumeration value="epr4m3tzr3c1"/>
                     <xsd:enumeration value="epr4m3tzr3c2"/>
                     <xsd:enumeration value="epr4m3tzr3c3"/>
                     <xsd:enumeration value="epr4m3thr1c1"/>
                     <xsd:enumeration value="epr4m3thr1c2"/>
                     <xsd:enumeration value="epr4m3thr2c3"/>
                     <xsd:enumeration value="epr4m3thr3c3"/>
                     <xsd:enumeration value="epr4m3tur1c1"/>
                     <xsd:enumeration value="epr4m3tir1c1"/>
                     <xsd:enumeration value="epr4m3tir2c1"/>
                     <xsd:enumeration value="epr4m3tir3c1"/>
                     <xsd:enumeration value="epr4m3tir4c1"/>
                     <xsd:enumeration value="epr4m3tkr1c1"/>
                     <xsd:enumeration value="epr4m3tkr1c2"/>
                     <xsd:enumeration value="epr4m4tar1c1"/>
                     <xsd:enumeration value="epr4m4tar1c2"/>
                     <xsd:enumeration value="epr4m4tar1c3"/>
                     <xsd:enumeration value="epr4m4tar2c1"/>
                     <xsd:enumeration value="epr4m4tar2c2"/>
                     <xsd:enumeration value="epr4m4tar2c3"/>
                     <xsd:enumeration value="epr4m4tar3c1"/>
                     <xsd:enumeration value="epr4m4tar3c2"/>
                     <xsd:enumeration value="epr4m4tar3c3"/>
                     <xsd:enumeration value="epr4m4tar5c1"/>
                     <xsd:enumeration value="epr4m4tar5c2"/>
                     <xsd:enumeration value="epr4m4tar5c3"/>
                     <xsd:enumeration value="epr4m4tar6c1"/>
                     <xsd:enumeration value="epr4m4tar6c2"/>
                     <xsd:enumeration value="epr4m4tar6c3"/>
                     <xsd:enumeration value="epr4m4tar7c1"/>
                     <xsd:enumeration value="epr4m4tar7c2"/>
                     <xsd:enumeration value="epr4m4tar7c3"/>
                     <xsd:enumeration value="epr4m4tar7ac1"/>
                     <xsd:enumeration value="epr4m4tar7ac2"/>
                     <xsd:enumeration value="epr4m4tar7ac3"/>
                     <xsd:enumeration value="epr4m4tar8c1"/>
                     <xsd:enumeration value="epr4m4tar8c2"/>
                     <xsd:enumeration value="epr4m4tar8c3"/>
                     <xsd:enumeration value="epr4m4tar8ac3"/>
                     <xsd:enumeration value="epr4m4tar8bc3"/>
                     <xsd:enumeration value="epr4m4tar9c1"/>
                     <xsd:enumeration value="epr4m4tar9c2"/>
                     <xsd:enumeration value="epr4m4tbr1c1"/>
                     <xsd:enumeration value="epr4m4tbr2c1"/>
                     <xsd:enumeration value="epr4m4tbr3c1"/>
                     <xsd:enumeration value="epr4m4tbr5c1"/>
                     <xsd:enumeration value="epr4m4tbr7c1"/>
                     <xsd:enumeration value="epr4m4tbr8c1"/>
                     <xsd:enumeration value="epr4m4tcr2c1"/>
                     <xsd:enumeration value="epr4m4tcr2c2"/>
                     <xsd:enumeration value="epr4m4tdr1c1"/>
                     <xsd:enumeration value="epr4m4tdr1c2"/>
                     <xsd:enumeration value="epr4m4tdr2c1"/>
                     <xsd:enumeration value="epr4m4tdr2c2"/>
                     <xsd:enumeration value="epr4m4tdr3c1"/>
                     <xsd:enumeration value="epr4m4tdr3c2"/>
                     <xsd:enumeration value="epr4m4ter1c1"/>
                     <xsd:enumeration value="epr4m4ter1c2"/>
                     <xsd:enumeration value="epr4m4ter1ac2"/>
                     <xsd:enumeration value="epr4m4ter2c1"/>
                     <xsd:enumeration value="epr4m4ter3c1"/>
                     <xsd:enumeration value="epr4m4ter4c1"/>
                     <xsd:enumeration value="epr4m4ter5c1"/>
                     <xsd:enumeration value="epr4m4tzr1c1"/>
                     <xsd:enumeration value="epr4m4tzr1c2"/>
                     <xsd:enumeration value="epr4m4tzr2c1"/>
                     <xsd:enumeration value="epr4m4thr1c1"/>
                     <xsd:enumeration value="epr4m4thr1c2"/>
                     <xsd:enumeration value="epr4m4thr2c1"/>
                     <xsd:enumeration value="epr4m4tur1ac1"/>
                     <xsd:enumeration value="epr4m4tur1ac2"/>
                     <xsd:enumeration value="epr4m4tur1c1"/>
                     <xsd:enumeration value="epr4m4tur1c2"/>
                     <xsd:enumeration value="epr4m4tur2c1"/>
                     <xsd:enumeration value="epr4m4tur2c2"/>
                     <xsd:enumeration value="epr4m4tur3c1"/>
                     <xsd:enumeration value="epr4m4tur3c2"/>
                     <xsd:enumeration value="epr4m4tur4c1"/>
                     <xsd:enumeration value="epr4m4tur4c2"/>
                     <xsd:enumeration value="epr4m4tir2c2"/>
                     <xsd:enumeration value="epr4m4tir2c3"/>
                     <xsd:enumeration value="epr4m4tir2c4"/>
                     <xsd:enumeration value="epr4m4tir2c5"/>
                     <xsd:enumeration value="epr4m5tb1r1c1"/>
                     <xsd:enumeration value="epr4m5tb1r1c2"/>
                     <xsd:enumeration value="epr4m5tb1r1ac1"/>
                     <xsd:enumeration value="epr4m5tb1r1ac2"/>
                     <xsd:enumeration value="epr4m5tb1r1bc1"/>
                     <xsd:enumeration value="epr4m5tb1r1bc2"/>
                     <xsd:enumeration value="epr4m5tb1r2c1"/>
                     <xsd:enumeration value="epr4m5tb1r2c2"/>
                     <xsd:enumeration value="epr4m5tb1r3c1"/>
                     <xsd:enumeration value="epr4m5tb1r3c2"/>
                     <xsd:enumeration value="epr4m5tb1r4c1"/>
                     <xsd:enumeration value="epr4m5tb1r4c2"/>
                     <xsd:enumeration value="epr4m5tb1r4ac2"/>
                     <xsd:enumeration value="epr4m5tb1r4bc1"/>
                     <xsd:enumeration value="epr4m5tb1r4bc2"/>
                     <xsd:enumeration value="epr4m5tb1r5c1"/>
                     <xsd:enumeration value="epr4m5tb1r5c2"/>
                     <xsd:enumeration value="epr4m5tb1r6c1"/>
                     <xsd:enumeration value="epr4m5tb1r6c2"/>
                     <xsd:enumeration value="epr4m5tb1r6c3"/>
                     <xsd:enumeration value="epr4m5tb1r6c4"/>
                     <xsd:enumeration value="epr4m5tb1r6c5"/>
                     <xsd:enumeration value="epr4m5tb1r6c6"/>
                     <xsd:enumeration value="epr4m5tb1r6c7"/>
                     <xsd:enumeration value="epr4m5tb1r6c8"/>
                     <xsd:enumeration value="epr4m5tb1r6bc1"/>
                     <xsd:enumeration value="epr4m5tb1r6cc1"/>
                     <xsd:enumeration value="epr4m5tb1r6dc1"/>
                     <xsd:enumeration value="epr4m5tb1ar1c1"/>
                     <xsd:enumeration value="epr4m5tb1ar2c1"/>
                     <xsd:enumeration value="epr4m5tb1ar3c1"/>
                     <xsd:enumeration value="epr4m5tb1r9c1"/>
                     <xsd:enumeration value="epr4m5tb1r7c1"/>
                     <xsd:enumeration value="epr4m5tb1r7c2"/>
                     <xsd:enumeration value="epr4m5tb2r1ac4"/>
                     <xsd:enumeration value="epr4m5tb1r8c1"/>
                     <xsd:enumeration value="epr4m5tb2r2c1"/>
                     <xsd:enumeration value="epr4m5tb2r2c2"/>
                     <xsd:enumeration value="epr4m5tb2r3c1"/>
                     <xsd:enumeration value="epr4m5tb2r3c2"/>
                     <xsd:enumeration value="epr4m5tb2r4c1"/>
                     <xsd:enumeration value="epr4m5tb2r4c2"/>
                     <xsd:enumeration value="epr4m5tb2r5c1"/>
                     <xsd:enumeration value="epr4m5tb2r5c2"/>
                     <xsd:enumeration value="epr4m5tb2r6c1"/>
                     <xsd:enumeration value="epr4m5tb2r7c1"/>
                     <xsd:enumeration value="epr4m5tb3r1c1"/>
                     <xsd:enumeration value="epr4m5tb3r1c2"/>
                     <xsd:enumeration value="epr4m5tb3r2c2"/>
                     <xsd:enumeration value="epr4m5tb3r3c1"/>
                     <xsd:enumeration value="epr4m5tb3r3c2"/>
                     <xsd:enumeration value="epr4m5tb3r4c1"/>
                     <xsd:enumeration value="epr4m5tb3r4c2"/>
                     <xsd:enumeration value="epr4m5tb3r4bc1"/>
                     <xsd:enumeration value="epr4m5tb3r4bc2"/>
                     <xsd:enumeration value="epr4m5tb3r4cc1"/>
                     <xsd:enumeration value="epr4m5tb3r4cc2"/>
                     <xsd:enumeration value="epr4m5tb3r5c1"/>
                     <xsd:enumeration value="epr4m5tb3r5c2"/>
                     <xsd:enumeration value="epr4m5tb3r6c1"/>
                     <xsd:enumeration value="epr4m5tb3r7c1"/>
                     <xsd:enumeration value="epr4m5tb4r1ac1"/>
                     <xsd:enumeration value="epr4m5tb4r1c1"/>
                     <xsd:enumeration value="epr4m5tb4r2c1"/>
                     <xsd:enumeration value="epr4m5tb4r2c2"/>
                     <xsd:enumeration value="epr4m5tb4r3c1"/>
                     <xsd:enumeration value="epr4m5tb4r4c1"/>
                     <xsd:enumeration value="epr4m5tb4r5c1"/>
                     <xsd:enumeration value="epr4m5tb4r5c2"/>
                     <xsd:enumeration value="epr4m5tb4r6c1"/>
                     <xsd:enumeration value="epr4m5tb4r6c2"/>
                     <xsd:enumeration value="epr4m5tb4r7c1"/>
                     <xsd:enumeration value="epr4m5tb4r8c1"/>
                     <xsd:enumeration value="epr4m5tb6r1c1"/>
                     <xsd:enumeration value="epr4m7t0r1c1"/>
                     <xsd:enumeration value="epr4m7t0r1c2"/>
                     <xsd:enumeration value="epr4m7t0r2c1"/>
                     <xsd:enumeration value="epr4m7t0r3c1"/>
                     <xsd:enumeration value="epr4m7t0r4c1"/>
                     <xsd:enumeration value="epr4m8t0r1c1"/>
                     <xsd:enumeration value="epr4m8t0r1c2"/>
                     <xsd:enumeration value="epr4m8t0r2c1"/>
                     <xsd:enumeration value="epr4m8t0r2c2"/>
                     <xsd:enumeration value="epr4m8t0r3ac1"/>
                     <xsd:enumeration value="epr4m8t0r3c1"/>
                     <xsd:enumeration value="epr4m8t0r4c1"/>
                     <xsd:enumeration value="epr4m8t0r5c1"/>
                     <xsd:enumeration value="epr4m8t0r6c1"/>
                     <xsd:enumeration value="epr4m8t0r6c2"/>
                     <xsd:enumeration value="epr4m8t0r6c3"/>
                     <xsd:enumeration value="epr4m8t0r6c4"/>
                     <xsd:enumeration value="epr4m8t0r6c5"/>
                     <xsd:enumeration value="epr4m8t0r7c1"/>
                     <xsd:enumeration value="epr4m8t0r8c1"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
   
   <xsd:complexType name="epr42024GridKeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης ΕΠΡ4 2024 το οποίο περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required">
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου σε πίνακα της δήλωσης ΕΠΡ4 2024. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                  	  <xsd:enumeration value="epr4m1ter10c1"/>
                      <xsd:enumeration value="epr4m1ter10c2"/>
                      <xsd:enumeration value="epr4m1ter10c3"/>
                      <xsd:enumeration value="epr4m1ter10c4"/>
                      <xsd:enumeration value="epr4m1ter10c5"/>
                      <xsd:enumeration value="epr4m1ter10c6"/>
                      <xsd:enumeration value="epr4m1ter10c7"/>
                      <xsd:enumeration value="epr4m2tc7r8c1"/>
                      <xsd:enumeration value="epr4m2tc7r8c2"/>
                      <xsd:enumeration value="epr4m2tc7r8c3"/>
                      <xsd:enumeration value="epr4m2tc7r8c4"/>
                      <xsd:enumeration value="epr4m2tc7r8c5"/>
                      <xsd:enumeration value="epr4m2tc7r8c6"/>
				 	  <xsd:enumeration value="epr4m2tc10r1c1"/>
				      <xsd:enumeration value="epr4m2tc10r1c2"/>
				      <xsd:enumeration value="epr4m2tc10r1c3"/>
				      <xsd:enumeration value="epr4m2tc10r1c4"/>
				      <xsd:enumeration value="epr4m2tc10r1c5"/>
				      <xsd:enumeration value="epr4m2tc10r1c6"/>
				      <xsd:enumeration value="epr4m2tc11r1c1"/>
				      <xsd:enumeration value="epr4m2tc11r1c1a"/>
				      <xsd:enumeration value="epr4m2tc11r1c2"/>
				      <xsd:enumeration value="epr4m2tc11r1c3"/>
				      <xsd:enumeration value="epr4m2tc11r1c5"/>
				      <xsd:enumeration value="epr4m2tc11r1c7"/>
				      <xsd:enumeration value="epr4m2tc11r1c8"/>
				      <xsd:enumeration value="epr4m2tc14r1c1"/>
				      <xsd:enumeration value="epr4m2tc14r1c2"/>
				      <xsd:enumeration value="epr4m2tc14r1c3"/>
				      <xsd:enumeration value="epr4m2tc14r1c4"/>
				      <xsd:enumeration value="epr4m2tc14r1c5"/>
				      <xsd:enumeration value="epr4m2tc14r1c6"/>
				      <xsd:enumeration value="epr4m2tc14r1c7"/>
				      <xsd:enumeration value="epr4m2tc14r1c8"/>
				      <xsd:enumeration value="epr4m2tc14r1c9"/>
				      <xsd:enumeration value="epr4m2tc16r3c1"/>
				      <xsd:enumeration value="epr4m2tc16r3c2"/>
				      <xsd:enumeration value="epr4m2tc20r1c1"/>
				      <xsd:enumeration value="epr4m2tc20r1c2"/>
				      <xsd:enumeration value="epr4m2tc20r1c3"/>
				      <xsd:enumeration value="epr4m2tc20r1c4"/>
				      <xsd:enumeration value="epr4m2tc20r1c5"/>
				      <xsd:enumeration value="epr4m2tc20r1c6"/>
				      <xsd:enumeration value="epr4m2tc20br1c1"/>
				      <xsd:enumeration value="epr4m2tc20br1c2"/>
				      <xsd:enumeration value="epr4m2tc20br1c3"/>
				      <xsd:enumeration value="epr4m2tc20br1c4"/>
				      <xsd:enumeration value="epr4m2tc20br1c5"/>
				      <xsd:enumeration value="epr4m2tc20br1c6"/>
				      <xsd:enumeration value="epr4m2tc20br1c7"/>
				      <xsd:enumeration value="epr4m2tc20br1c8"/>
				      <xsd:enumeration value="epr4m2tc20br1c9"/>
				      <xsd:enumeration value="epr4m4tbr4c1"/>
				      <xsd:enumeration value="epr4m4tbr4c2"/>
				      <xsd:enumeration value="epr4m4tbr4c3"/>
				      <xsd:enumeration value="epr4m4tbr4c4"/>
				      <xsd:enumeration value="epr4m4tbr6c1"/>
				      <xsd:enumeration value="epr4m4tbr6c2"/>
				      <xsd:enumeration value="epr4m4tbr6c3"/>
				      <xsd:enumeration value="epr4m4tbr6c4"/>
				      <xsd:enumeration value="epr4m4tir1c1"/>
				      <xsd:enumeration value="epr4m4tir1c2"/>
				      <xsd:enumeration value="epr4m4tir1c3"/>
				      <xsd:enumeration value="epr4m4tir1c4"/>
				      <xsd:enumeration value="epr4m4tir1c5"/>
				      <xsd:enumeration value="epr4m5tb2r1c2"/>
				      <xsd:enumeration value="epr4m5tb2r1c3"/>
				      <xsd:enumeration value="epr4m5tb2r1c4"/>
				      <xsd:enumeration value="epr4m6t0r1c1"/>
				      <xsd:enumeration value="epr4m6t0r1c2"/>
				      <xsd:enumeration value="epr4m6t0r1c3"/>
				      <xsd:enumeration value="epr4m6t0r1c4"/>
				      <xsd:enumeration value="epr4m6t0r1c5"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
	
</xsd:schema>
