<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	targetNamespace="http://www.mof.gov.cy" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	elementFormDefault="qualified" 
	xmlns:olive="http://www.intracom.gr/olive" 
	xmlns:mof="http://www.mof.gov.cy">

	<xsd:annotation>
		<xsd:documentation xml:lang="EL">Το παρόν XML schema περιέχει
		ορισμούς τύπων οι οποίοι πρόκειται να χρησιμοποιηθούν
		για την αναπαράσταση δήλωσης Τ.Φ.1 Αυτεργοδοτούμενου Φορολογικού Έτους 2024
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:import schemaLocation="olive-core.xsd" namespace="http://www.intracom.gr/olive"></xsd:import>
	<xsd:import namespace="http://www.intracom.gr/olive" schemaLocation="olive-core.xsd" />
	
	 <xsd:complexType name="epr1a2024KeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης Τ.Φ.1 Αυτεργοδοτούμενου 2024 ανεξαρτήτως μέρους το οποίο δεν περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required" >
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου της δήλωσης Τ.Φ.1 Αυτεργοδοτούμενου 2024 το οποίο δεν περιέχεται σε πίνακα. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                     <xsd:enumeration value="epr1am1t0r1c1"/>
                     <xsd:enumeration value="epr1am2tar1c1"/>
                     <xsd:enumeration value="epr1am2tar2c1"/>
                     <xsd:enumeration value="epr1am2tar2c2"/>
                     <xsd:enumeration value="epr1am2tbr1c1"/>
                     <xsd:enumeration value="epr1am2tbr2c1"/>
                     <xsd:enumeration value="epr1am2tbr4c3"/>
                     <xsd:enumeration value="epr1am3tar1c1"/>
                     <xsd:enumeration value="epr1am3tar2c1"/>
                     <xsd:enumeration value="epr1am3tb1r1c1"/>
					 <xsd:enumeration value="epr1am3tb1r1c2"/>
					 <xsd:enumeration value="epr1am3tb1r1c3"/>
					 <xsd:enumeration value="epr1am3tb2r1c1"/>
					 <xsd:enumeration value="epr1am3tb2r2c1"/>
					 <xsd:enumeration value="epr1am3tb2r3c1"/>
					 <xsd:enumeration value="epr1am3tb2r3c2"/>
					 <xsd:enumeration value="epr1am3tb2r3c2b"/>
					 <xsd:enumeration value="epr1am3tb2r3c2c"/>
					 <xsd:enumeration value="epr1am3tb2r3c3"/>
					 <xsd:enumeration value="epr1am3tb2r3c4"/>
					 <xsd:enumeration value="epr1am3tb2r4c1"/>
					 <xsd:enumeration value="epr1am3tb3r1c1"/>
				 	 <xsd:enumeration value="epr1am3tb3r1c2"/>
                     <xsd:enumeration value="epr1am3tbr1c1y04"/>
                     <xsd:enumeration value="epr1am3tbr2c1y04"/>
                     <xsd:enumeration value="epr1am4ta1r1c1"/>
                     <xsd:enumeration value="epr1am4ta1r1ac1"/>
                     <xsd:enumeration value="epr1am4ta1r2c1"/>
                     <xsd:enumeration value="epr1am4ta1r2c2"/>
                     <xsd:enumeration value="epr1am4ta1r2c3"/>
                     <xsd:enumeration value="epr1am4ta1r2c4"/>
                     <xsd:enumeration value="epr1am4ta1r4c1"/>
                     <xsd:enumeration value="epr1am4ta1r4c2"/>
                     <xsd:enumeration value="epr1am4ta1r4c3"/>
                     <xsd:enumeration value="epr1am4ta1r5ac1"/>
                     <xsd:enumeration value="epr1am4ta1r5c1"/>
                     <xsd:enumeration value="epr1am4ta2r1c2"/>
                     <xsd:enumeration value="epr1am4ta2r1c3"/>
                     <xsd:enumeration value="epr1am4ta2r2c2"/>
                     <xsd:enumeration value="epr1am4ta2r2c3"/>
                     <xsd:enumeration value="epr1am4ta2r3c1"/>
                     <xsd:enumeration value="epr1am4ta2r4c1"/>
                     <xsd:enumeration value="epr1am4ta3r2c1"/>
                     <xsd:enumeration value="epr1am4ta3r2c2"/>
                     <xsd:enumeration value="epr1am4ta3r2c3"/>
                     <xsd:enumeration value="epr1am4ta3r2c4"/>
                     <xsd:enumeration value="epr1am4ta3r2c5"/>
                     <xsd:enumeration value="epr1am4ta3r2c6"/>
                     <xsd:enumeration value="epr1am4tbr2c1"/>
                     <xsd:enumeration value="epr1am4tbr2c2"/>
                     <xsd:enumeration value="epr1am4tbr2c3"/>
                     <xsd:enumeration value="epr1am4tbr3c1"/>
                     <xsd:enumeration value="epr1am4tbr4c1"/>
                     <xsd:enumeration value="epr1am4tcr2c1"/>
                     <xsd:enumeration value="epr1am4tcr2c2"/>
                     <xsd:enumeration value="epr1am4tcr2c3"/>
                     <xsd:enumeration value="epr1am4tcr2c4"/>
                     <xsd:enumeration value="epr1am4tcr2c6"/>
                     <xsd:enumeration value="epr1am4tcr2c7"/>
                     <xsd:enumeration value="epr1am4tcr2c8"/>
                     <xsd:enumeration value="epr1am4tdr2c1"/>
                     <xsd:enumeration value="epr1am4tdr2c2"/>
                     <xsd:enumeration value="epr1am4tdr2c3"/>
                     <xsd:enumeration value="epr1am4ter2c1"/>
                     <xsd:enumeration value="epr1am4ter2c2"/>
                     <xsd:enumeration value="epr1am4ter2c3"/>
                     <xsd:enumeration value="epr1am4ter2c4"/>
                     <xsd:enumeration value="epr1am4tzr2c1"/>
                     <xsd:enumeration value="epr1am4tzr2c2"/>
                     <xsd:enumeration value="epr1am4tzr2c2a"/>
                     <xsd:enumeration value="epr1am4tzr2c3"/>
                     <xsd:enumeration value="epr1am4thr2c1"/>
                     <xsd:enumeration value="epr1am4tjr2c1"/>
					 <xsd:enumeration value="epr1am4tjr2c2"/>
					 <xsd:enumeration value="epr1am4tjr2c3"/>
                     <xsd:enumeration value="epr1am4tur2c1"/>
                     <xsd:enumeration value="epr1am4tur2c2"/>
                     <xsd:enumeration value="epr1am4tur2c3"/>
                     <xsd:enumeration value="epr1am4tur2c4"/>
                     <xsd:enumeration value="epr1am4tur4c1"/>
                     <xsd:enumeration value="epr1am4tur5c1"/>
                     <xsd:enumeration value="epr1am4tur5c2"/>
                     <xsd:enumeration value="epr1am4tur6c1"/>
                     <xsd:enumeration value="epr1am4tur7c1"/>
                     <xsd:enumeration value="epr1am4tur9c1"/>
                     <xsd:enumeration value="epr1am4tur10c1"/>
                     <xsd:enumeration value="epr1am4tur10c1b"/>
                     <xsd:enumeration value="epr1am4tur10c1c"/>
                     <xsd:enumeration value="epr1am4tur11c1"/>
                     <xsd:enumeration value="epr1am4tur12c1"/>
                     <xsd:enumeration value="epr1am4tur12c1b"/>
                     <xsd:enumeration value="epr1am4tur13c1"/>
                     <xsd:enumeration value="epr1am4tur14c1"/>
                     <xsd:enumeration value="epr1am4tur15c1"/>
                     <xsd:enumeration value="epr1am4tur16c1"/>
                     <xsd:enumeration value="epr1am4tur3c1"/>
                     <xsd:enumeration value="epr1am4tur8c1"/>
                     <xsd:enumeration value="epr1am4tir1c1"/>
                     <xsd:enumeration value="epr1am5tbr1c1"/>
                     <xsd:enumeration value="epr1am5tbr2c1"/>
                     <xsd:enumeration value="epr1am5tbr3c1"/>
                     <xsd:enumeration value="epr1am5tbr3bc1"/>
                     <xsd:enumeration value="epr1am5tbr3cc1"/>
                     <xsd:enumeration value="epr1am5tbr4c1"/>
                     <xsd:enumeration value="epr1am5tbr5c1"/>
                     <xsd:enumeration value="epr1am5tcr2c1"/>
                     <xsd:enumeration value="epr1am5tcr2c2"/>
                     <xsd:enumeration value="epr1am5tcr2c3"/>
                     <xsd:enumeration value="epr1am5tcr2c4"/>
                     <xsd:enumeration value="epr1am5tdr3c1"/>
                     <xsd:enumeration value="epr1am6ta1r1c1"/>
                     <xsd:enumeration value="epr1am6ta1r2c1"/>
                     <xsd:enumeration value="epr1am6ta1r3c1"/>
                     <xsd:enumeration value="epr1am6ta1r4c1"/>
                     <xsd:enumeration value="epr1am6tar1c1y04"/>
                     <xsd:enumeration value="epr1am6tar2c1y04"/>
                     <xsd:enumeration value="epr1am6tar1c1"/>
                     <xsd:enumeration value="epr1am6tar2c1"/>
                     <xsd:enumeration value="epr1am6tar4c1"/>
					 <xsd:enumeration value="epr1am6tar4c2"/>
					 <xsd:enumeration value="epr1am6tar4c3"/>
					 <xsd:enumeration value="epr1am6tar5c1"/>
					 <xsd:enumeration value="epr1am6tar5c2"/>
					 <xsd:enumeration value="epr1am6tar5c3"/>
                     <xsd:enumeration value="epr1am6tbr1ac1"/>
                     <xsd:enumeration value="epr1am6tbr1bc1"/>
                     <xsd:enumeration value="epr1am6tbr1cc1"/>
                     <xsd:enumeration value="epr1am6tbr1dc1"/>
                     <xsd:enumeration value="epr1am6tbr1c1"/>
                     <xsd:enumeration value="epr1am6tbr1c2"/>
                     <xsd:enumeration value="epr1am6tbr2c1"/>
                     <xsd:enumeration value="epr1am6tbr3c1"/>
                     <xsd:enumeration value="epr1am6tbr4c1"/>
                     <xsd:enumeration value="epr1am6tbr6c1"/>
                     <xsd:enumeration value="epr1am6tbr7c1"/>
                     <xsd:enumeration value="epr1am6tbr8c1"/>
                     <xsd:enumeration value="epr1am6tbr11c1"/>
                     <xsd:enumeration value="epr1am6tbr12c1"/>
                     <xsd:enumeration value="epr1am6tbr12c2"/>
                     <xsd:enumeration value="epr1am6tbr13c1"/>
                     <xsd:enumeration value="epr1am6tbr14c1"/>
                     <xsd:enumeration value="epr1am6tbr13c2"/>
                     <xsd:enumeration value="epr1am6tbr14c2"/>
                     <xsd:enumeration value="epr1am6tbr15c1"/>
                     <xsd:enumeration value="epr1am6tbr16c1"/>
                     <xsd:enumeration value="epr1am6tbr17c1"/>
                     <xsd:enumeration value="epr1am6tbr18c1"/>
                     <xsd:enumeration value="epr1am6tbr19c1"/>
                     <xsd:enumeration value="epr1am6tbr20c1"/>
                     <xsd:enumeration value="epr1am6tdr1c1"/>
                     <xsd:enumeration value="epr1am6tdr2c1"/>
                     <xsd:enumeration value="epr1am6tdr2bc1"/>
                     <xsd:enumeration value="epr1am6tdr3c1"/>
                     <xsd:enumeration value="epr1am6tdr3bc1"/>
                     <xsd:enumeration value="epr1am6tdr4c1"/>
                     <xsd:enumeration value="epr1am6tdr5c1"/>
                     <xsd:enumeration value="epr1am6tdr6c1"/>
                     <xsd:enumeration value="epr1am6tdr7c1"/>
                     <xsd:enumeration value="epr1am6tdr8c1"/>
                     <xsd:enumeration value="epr1am6tdr9c1"/>
                     <xsd:enumeration value="epr1am6tdr10c1"/>
                     <xsd:enumeration value="epr1am6tdr11c1"/>
                     <xsd:enumeration value="epr1am6tdr12c1"/>
                     <xsd:enumeration value="epr1am7t2ar2c1"/>
                     <xsd:enumeration value="epr1am7t2ar2c2"/>
                     <xsd:enumeration value="epr1am7t2ar2c3"/>
                     <xsd:enumeration value="epr1am7t2ar2c4"/>
                     <xsd:enumeration value="epr1am7t2ar2c5"/>
                     <xsd:enumeration value="epr1am7t2ar2c6"/>
                     <xsd:enumeration value="epr1am7t2ar2c7"/>
                     <xsd:enumeration value="epr1am7t2ar1c1"/>
					 <xsd:enumeration value="epr1am7t2ar1c2"/>
					 <xsd:enumeration value="epr1am7t2ar1c3"/>
		 			 <xsd:enumeration value="epr1am7t2ar1c4"/>
		 			 <xsd:enumeration value="epr1am7t2ar1c5"/>
					 <xsd:enumeration value="epr1am7t2ar1c6"/>
					 <xsd:enumeration value="epr1am7t2ar1c7"/>
					 <xsd:enumeration value="epr1am7t2br1c1"/>
					 <xsd:enumeration value="epr1am7t2br1c2"/>
					 <xsd:enumeration value="epr1am7t2br1c3"/>
					 <xsd:enumeration value="epr1am7t2br1c4"/>
					 <xsd:enumeration value="epr1am7t2br1c5"/>
					 <xsd:enumeration value="epr1am7t2br1c6"/>
					 <xsd:enumeration value="epr1am7t2br1c7"/>
					 <xsd:enumeration value="epr1am7t2br2c1"/>
					 <xsd:enumeration value="epr1am7t2br2c2"/>
					 <xsd:enumeration value="epr1am7t2br2c3"/>
					 <xsd:enumeration value="epr1am7t2br2c4"/>
					 <xsd:enumeration value="epr1am7t2br2c5"/>
					 <xsd:enumeration value="epr1am7t2br2c6"/>
					 <xsd:enumeration value="epr1am7t2br2c7"/>
					 <xsd:enumeration value="epr1am7t2br3c1"/>
					 <xsd:enumeration value="epr1am7t2br3c2"/>
					 <xsd:enumeration value="epr1am7t2br3c3"/>
					 <xsd:enumeration value="epr1am7t2br3c4"/>
					 <xsd:enumeration value="epr1am7t2br3c5"/>
					 <xsd:enumeration value="epr1am7t2br3c6"/>
					 <xsd:enumeration value="epr1am7t2br3c7"/>
					 <xsd:enumeration value="epr1am7t2cr1c1"/>
					 <xsd:enumeration value="epr1am7t2cr1c2"/>
					 <xsd:enumeration value="epr1am7t2cr1c3"/>
					 <xsd:enumeration value="epr1am7t2cr1c4"/>
					 <xsd:enumeration value="epr1am7t2cr1c5"/>
					 <xsd:enumeration value="epr1am7t2cr1c6"/>
					 <xsd:enumeration value="epr1am7t2cr1c7"/>
					 <xsd:enumeration value="epr1am7t2dr1c2"/>
					 <xsd:enumeration value="epr1am7t2dr1c7"/>
					 <xsd:enumeration value="epr1am7t2er1c1"/>
					 <xsd:enumeration value="epr1am7t2er1c2"/>
					 <xsd:enumeration value="epr1am7t2er1c3"/>
					 <xsd:enumeration value="epr1am7t2er1c4"/>
					 <xsd:enumeration value="epr1am7t2er1c5"/>
					 <xsd:enumeration value="epr1am7t2er1c6"/>
					 <xsd:enumeration value="epr1am7t2er1c7"/>
					 <xsd:enumeration value="epr1am7t2er2c2"/>
					 <xsd:enumeration value="epr1am7t2er2c7"/>
					 <xsd:enumeration value="epr1am7t2er3c1"/>
					 <xsd:enumeration value="epr1am7t2er3c2"/>
					 <xsd:enumeration value="epr1am7t2er3c3"/>
					 <xsd:enumeration value="epr1am7t2er3c4"/>
					 <xsd:enumeration value="epr1am7t2er3c5"/>
					 <xsd:enumeration value="epr1am7t2er3c6"/>
					 <xsd:enumeration value="epr1am7t2er3c7"/>
					 <xsd:enumeration value="epr1am7t2er4c1"/>
					 <xsd:enumeration value="epr1am7t2er4c2"/>
					 <xsd:enumeration value="epr1am7t2er4c3"/>
					 <xsd:enumeration value="epr1am7t2er4c4"/>
					 <xsd:enumeration value="epr1am7t2er4c5"/>
					 <xsd:enumeration value="epr1am7t2er4c6"/>
					 <xsd:enumeration value="epr1am7t2er4c7"/>
					 <xsd:enumeration value="epr1am7t2fr1c1"/>
					 <xsd:enumeration value="epr1am7t2fr1c2"/>
					 <xsd:enumeration value="epr1am7t2fr1c3"/>
					 <xsd:enumeration value="epr1am7t2fr1c4"/>
					 <xsd:enumeration value="epr1am7t2fr1c5"/>
					 <xsd:enumeration value="epr1am7t2fr1c6"/>
					 <xsd:enumeration value="epr1am7t2fr1c7"/>
					 <xsd:enumeration value="epr1am7t2gr1c1"/>
					 <xsd:enumeration value="epr1am7t2gr1c2"/>
					 <xsd:enumeration value="epr1am7t2gr1c3"/>
					 <xsd:enumeration value="epr1am7t2gr1c4"/>
					 <xsd:enumeration value="epr1am7t2gr1c5"/>
					 <xsd:enumeration value="epr1am7t2gr1c6"/>
					 <xsd:enumeration value="epr1am7t2gr1c7"/>
					 <xsd:enumeration value="epr1am7t2gr2c1"/>
					 <xsd:enumeration value="epr1am7t2gr2c2"/>
					 <xsd:enumeration value="epr1am7t2gr2c3"/>
					 <xsd:enumeration value="epr1am7t2gr2c4"/>
					 <xsd:enumeration value="epr1am7t2gr2c5"/>
					 <xsd:enumeration value="epr1am7t2gr2c6"/>
					 <xsd:enumeration value="epr1am7t2gr2c7"/>
					 <xsd:enumeration value="epr1am7t2gr3c1"/>
					 <xsd:enumeration value="epr1am7t2gr3c2"/>
					 <xsd:enumeration value="epr1am7t2gr3c3"/>
					 <xsd:enumeration value="epr1am7t2gr3c4"/>
					 <xsd:enumeration value="epr1am7t2gr3c5"/>
					 <xsd:enumeration value="epr1am7t2gr3c6"/>
					 <xsd:enumeration value="epr1am7t2gr3c7"/>
					 <xsd:enumeration value="epr1am7t2hr1c1"/>
					 <xsd:enumeration value="epr1am7t2hr1c2"/>
					 <xsd:enumeration value="epr1am7t2hr1c3"/>
					 <xsd:enumeration value="epr1am7t2hr1c4"/>
                     <xsd:enumeration value="epr1am7t0r1c1"/>
                     <xsd:enumeration value="epr1am7t0r2c1"/>
                     <xsd:enumeration value="epr1am7t0r3c1"/>
                     <xsd:enumeration value="epr1am7t0r4c1"/>
                     <xsd:enumeration value="epr1am7t0r5c1"/>
                     <xsd:enumeration value="epr1am7t0r6c1"/>
                     <xsd:enumeration value="epr1am7t0r7c1"/>
                     <xsd:enumeration value="epr1am7t0r7c2"/>
                     <xsd:enumeration value="epr1am7t0r7c3"/>
                     <xsd:enumeration value="epr1am8t0r1c1"/>
                     <xsd:enumeration value="epr1am8t0r2c1"/>
                     <xsd:enumeration value="epr1am8t0r3c1"/>
                     <xsd:enumeration value="epr1am8t0r4ac1"/>
                     <xsd:enumeration value="epr1am8t0r4bc1"/>
                     <xsd:enumeration value="epr1am8t0r4cc1"/>
                     <xsd:enumeration value="epr1am8t0r4c1"/>
                     <xsd:enumeration value="epr1am8t0r5c1"/>
                     <xsd:enumeration value="epr1am8t0r6c1"/>
                     <xsd:enumeration value="epr1am8t0r7c1"/>
                     <xsd:enumeration value="epr1am8t0r7ac1"/>
                     <xsd:enumeration value="epr1am8t0r8c1"/>
                     <xsd:enumeration value="epr1am8t0r8ac1"/>
                     <xsd:enumeration value="epr1am8t0r9c1"/>
                     <xsd:enumeration value="epr1am8t0r10c1"/>
                     <xsd:enumeration value="epr1am8t0r11c1"/>
                     <xsd:enumeration value="epr1am8t0r12ac1"/>
                     <xsd:enumeration value="epr1am8t0r12c1"/>
                     <xsd:enumeration value="epr1am8t0r13c2"/>
                     <xsd:enumeration value="epr1am8t0r14c1"/>
                     <xsd:enumeration value="epr1am8t0r15ac1"/>
                     <xsd:enumeration value="epr1am8t0r15a2c1"/>
                   	 <xsd:enumeration value="epr1am8t0r15bc1"/>
                   	 <xsd:enumeration value="epr1am8t0r15cc1"/>
                   	 <xsd:enumeration value="epr1am8t0r15dc1"/>
                   	 <xsd:enumeration value="epr1am8t0r15dc2"/>
                   	 <xsd:enumeration value="epr1am8t0r15c1"/>
                     <xsd:enumeration value="epr1am8t0r16c1"/>
                     <xsd:enumeration value="epr1am8t0r17c1"/>
                     <xsd:enumeration value="epr1am8t0r18ac1"/>
                     <xsd:enumeration value="epr1am8t0r18ac2"/>                     
                     <xsd:enumeration value="epr1am8t0r18c1"/>
                     <xsd:enumeration value="epr1am8t0r18c2"/>
                     <xsd:enumeration value="epr1am8t0r18bc1"/>
                     <xsd:enumeration value="epr1am8t0r18bc2"/>
                     <xsd:enumeration value="epr1am8t0r19c2"/>
                     <xsd:enumeration value="epr1am8t0r20ac1"/>
                     <xsd:enumeration value="epr1am8t0r20c1"/>
                     <xsd:enumeration value="epr1am8t0r21ac1"/>
                     <xsd:enumeration value="epr1am8t0r21c1"/>
                     <xsd:enumeration value="epr1am8t0r22c1"/>
                     <xsd:enumeration value="epr1am8t0r22bc1"/>
                     <xsd:enumeration value="epr1am8t0r23c1"/>
                     <xsd:enumeration value="epr1am8t1r1c1"/>
                     <xsd:enumeration value="epr1am8t1r1c2"/>
                     <xsd:enumeration value="epr1am8t1r1c3"/>
                     <xsd:enumeration value="epr1am8t1r1c4"/>
                     <xsd:enumeration value="epr1am8t1r2c1"/>
                     <xsd:enumeration value="epr1am8t1r2c2"/>
                     <xsd:enumeration value="epr1am8t1r2c3"/>
                     <xsd:enumeration value="epr1am8t1r2c4"/>
                     <xsd:enumeration value="epr1am8t1r3c1"/>
                     <xsd:enumeration value="epr1am8t1r3c2"/>
                     <xsd:enumeration value="epr1am8t1r3c3"/>
                     <xsd:enumeration value="epr1am8t1r3c4"/>
                     <xsd:enumeration value="epr1am8t1r4c1"/>
                     <xsd:enumeration value="epr1am8t1r4c2"/>
                     <xsd:enumeration value="epr1am8t1r4c3"/>
                     <xsd:enumeration value="epr1am8t1r4c4"/>
                     <xsd:enumeration value="epr1am8t1r5c1"/>
                     <xsd:enumeration value="epr1am8t1r5c2"/>
                     <xsd:enumeration value="epr1am8t1r5c3"/>
                     <xsd:enumeration value="epr1am8t1r5c4"/>
                     <xsd:enumeration value="epr1am8t1r6c1"/>
                     <xsd:enumeration value="epr1am8t1r6c2"/>
                     <xsd:enumeration value="epr1am8t1r6c3"/>
                     <xsd:enumeration value="epr1am8t1r6c4"/>
                     <xsd:enumeration value="epr1am8t1r6ac1"/>
                     <xsd:enumeration value="epr1am8t1r6ac2"/>
                     <xsd:enumeration value="epr1am8t1r6ac3"/>
                     <xsd:enumeration value="epr1am8t1r6ac4"/>
                     <xsd:enumeration value="epr1am8t1r6ac5"/>
                     <xsd:enumeration value="epr1am8t1r6ac6"/>
                     <xsd:enumeration value="epr1am8t1r7c1"/>
                     <xsd:enumeration value="epr1am8t1r7c1a"/>
                     <xsd:enumeration value="epr1am8t1r7c1b"/>
                     <xsd:enumeration value="epr1am8t1r7c2"/>
                     <xsd:enumeration value="epr1am8t1r7c2a"/>
                     <xsd:enumeration value="epr1am8t1r7c2b"/>
                     <xsd:enumeration value="epr1am8t1r8c1"/>
                     <xsd:enumeration value="epr1am8t1r8c1a"/>
                     <xsd:enumeration value="epr1am8t1r8c1b"/>
                     <xsd:enumeration value="epr1am8t1r8c2"/>
                     <xsd:enumeration value="epr1am8t1r8c2a"/>
                     <xsd:enumeration value="epr1am8t1r8c2b"/>
                     <xsd:enumeration value="epr1am8t1r9c1"/>
                     <xsd:enumeration value="epr1am8t1r9c1a"/>
                     <xsd:enumeration value="epr1am8t1r9c1b"/>
                     <xsd:enumeration value="epr1am8t1r9c2"/>
                     <xsd:enumeration value="epr1am8t1r9c2a"/>
                     <xsd:enumeration value="epr1am8t1r9c2b"/>
                     <xsd:enumeration value="epr1am8t1r9ac1"/>
                     <xsd:enumeration value="epr1am8t1r9ac1a"/>
                     <xsd:enumeration value="epr1am8t1r9ac1b"/>
                     <xsd:enumeration value="epr1am8t1r9ac2"/>
                     <xsd:enumeration value="epr1am8t1r9ac2a"/>
                     <xsd:enumeration value="epr1am8t1r9ac2b"/>
                     <xsd:enumeration value="epr1am8t1r10c1"/>
                     <xsd:enumeration value="epr1am8t1r10c1a"/>
                     <xsd:enumeration value="epr1am8t1r10c1b"/>
                     <xsd:enumeration value="epr1am8t1r10c2"/>
                     <xsd:enumeration value="epr1am8t1r10c2a"/>
                     <xsd:enumeration value="epr1am8t1r10c2b"/>
                     <xsd:enumeration value="epr1am8t1r11c2"/>
                     <xsd:enumeration value="epr1am8t1r12c1"/>
                     <xsd:enumeration value="epr1am8t1r12c2"/>
                     <xsd:enumeration value="epr1am9t0r1c1"/>
                     <xsd:enumeration value="epr1am9t0r2c1"/>
                     <xsd:enumeration value="epr1am6tc1ar1ac1"/>
                     <xsd:enumeration value="epr1am6tc1ar1ac2"/>
                     <xsd:enumeration value="epr1am6tc1ar1ac3"/>
                     <xsd:enumeration value="epr1am6tc1ar1ac4"/>
                     <xsd:enumeration value="epr1am6tc1ar1ac5"/>
                     <xsd:enumeration value="epr1am6tc1ar1c1"/>
                     <xsd:enumeration value="epr1am6tc1ar1c2"/>
                     <xsd:enumeration value="epr1am6tc1ar1c3"/>
                     <xsd:enumeration value="epr1am6tc1ar1c4"/>
                     <xsd:enumeration value="epr1am6tc1ar1c5"/>
                     <xsd:enumeration value="epr1am6tc1ar2c1"/>
                     <xsd:enumeration value="epr1am6tc1ar2c2"/>
                     <xsd:enumeration value="epr1am6tc1ar2c3"/>
                     <xsd:enumeration value="epr1am6tc1ar2c4"/>
                     <xsd:enumeration value="epr1am6tc1ar2c5"/>
                     <xsd:enumeration value="epr1am6tc1ar3c1"/>
                     <xsd:enumeration value="epr1am6tc1ar3c2"/>
                     <xsd:enumeration value="epr1am6tc1ar3c3"/>
                     <xsd:enumeration value="epr1am6tc1ar3c4"/>
                     <xsd:enumeration value="epr1am6tc1ar3c5"/>
                     <xsd:enumeration value="epr1am6tc1ar4c1"/>
                     <xsd:enumeration value="epr1am6tc1ar4c2"/>
                     <xsd:enumeration value="epr1am6tc1ar4c3"/>
                     <xsd:enumeration value="epr1am6tc1ar4c4"/>
                     <xsd:enumeration value="epr1am6tc1ar4c5"/>
                     <xsd:enumeration value="epr1am6tc1ar5c1"/>
                     <xsd:enumeration value="epr1am6tc1ar5c2"/>
                     <xsd:enumeration value="epr1am6tc1ar5c3"/>
                     <xsd:enumeration value="epr1am6tc1ar5c4"/>
                     <xsd:enumeration value="epr1am6tc1ar5c5"/>
                     <xsd:enumeration value="epr1am6tc1ar6c1"/>
                     <xsd:enumeration value="epr1am6tc1ar6c2"/>
                     <xsd:enumeration value="epr1am6tc1ar6c3"/>
                     <xsd:enumeration value="epr1am6tc1ar6c4"/>
                     <xsd:enumeration value="epr1am6tc1ar6c5"/>
                     <xsd:enumeration value="epr1am6tc1ar7c1"/>
                     <xsd:enumeration value="epr1am6tc1ar7c2"/>
                     <xsd:enumeration value="epr1am6tc1ar7c3"/>
                     <xsd:enumeration value="epr1am6tc1ar7c4"/>
                     <xsd:enumeration value="epr1am6tc1ar7c5"/>
                     <xsd:enumeration value="epr1am6tc1br1c1"/>
                     <xsd:enumeration value="epr1am6tc1br1c2"/>
                     <xsd:enumeration value="epr1am6tc1br2c1"/>
                     <xsd:enumeration value="epr1am6tc1br2c2"/>
                     <xsd:enumeration value="epr1am6tc1br3c1"/>
                     <xsd:enumeration value="epr1am6tc1br3c2"/>
                     <xsd:enumeration value="epr1am6tc1br3c3"/>
                     <xsd:enumeration value="epr1am6tc1br3c4"/>
                     <xsd:enumeration value="epr1am6tc1br4c1"/>
                     <xsd:enumeration value="epr1am6tc1br4c2"/>
                     <xsd:enumeration value="epr1am6tc1br4c3"/>
                     <xsd:enumeration value="epr1am6tc1br4c4"/>
                     <xsd:enumeration value="epr1am6tc1br5c1"/>
                     <xsd:enumeration value="epr1am6tc1br5c2"/>
                     <xsd:enumeration value="epr1am6tc1br5c3"/>
                     <xsd:enumeration value="epr1am6tc1br5c4"/>
                     <xsd:enumeration value="epr1am6tc1br6c1"/>
                     <xsd:enumeration value="epr1am6tc1br6c2"/>
                     <xsd:enumeration value="epr1am6tc1br6c3"/>
                     <xsd:enumeration value="epr1am6tc1br6c4"/>
                     <xsd:enumeration value="epr1am6tc1br7c1"/>
                     <xsd:enumeration value="epr1am6tc1br7c2"/>
                     <xsd:enumeration value="epr1am6tc1br7c3"/>
                     <xsd:enumeration value="epr1am6tc1br7c4"/>
                     <xsd:enumeration value="epr1am6tc1br8c1"/>
                     <xsd:enumeration value="epr1am6tc1br8c2"/>
                     <xsd:enumeration value="epr1am6tc1br9c1"/>
                     <xsd:enumeration value="epr1am6tc1br9c2"/>
                     <xsd:enumeration value="epr1am6tc1br10c1"/>
                     <xsd:enumeration value="epr1am6tc1br10c2"/>
                     <xsd:enumeration value="epr1am6tc1br11c1"/>
                     <xsd:enumeration value="epr1am6tc1br11c2"/>
                     <xsd:enumeration value="epr1am6tc1cr1c1"/>
                     <xsd:enumeration value="epr1am6tc1cr1c2"/>
                     <xsd:enumeration value="epr1am6tc1cr1c3"/>
                     <xsd:enumeration value="epr1am6tc1cr1c4"/>
                     <xsd:enumeration value="epr1am6tc1cr2c1"/>
                     <xsd:enumeration value="epr1am6tc1cr2c2"/>
                     <xsd:enumeration value="epr1am6tc1cr2c3"/>
                     <xsd:enumeration value="epr1am6tc1cr2c4"/>
                     <xsd:enumeration value="epr1am6tc1cr3c1"/>
                     <xsd:enumeration value="epr1am6tc1cr3c2"/>
                     <xsd:enumeration value="epr1am6tc1cr3c3"/>
                     <xsd:enumeration value="epr1am6tc1cr3c4"/>
                     <xsd:enumeration value="epr1am6tc1cr4c1"/>
                     <xsd:enumeration value="epr1am6tc1cr4c2"/>
                     <xsd:enumeration value="epr1am6tc1cr4c3"/>
                     <xsd:enumeration value="epr1am6tc1cr4c4"/>
                     <xsd:enumeration value="epr1am6tc1cr5c1"/>
                     <xsd:enumeration value="epr1am6tc1cr5c2"/>
                     <xsd:enumeration value="epr1am6tc1cr5c3"/>
                     <xsd:enumeration value="epr1am6tc1cr5c4"/>
                     <xsd:enumeration value="epr1am6tc1cr6c1"/>
                     <xsd:enumeration value="epr1am6tc1cr6c2"/>
                     <xsd:enumeration value="epr1am6tc1cr6c3"/>
                     <xsd:enumeration value="epr1am6tc1cr6c4"/>
                     <xsd:enumeration value="epr1am6tc1cr7c1"/>
                     <xsd:enumeration value="epr1am6tc1cr7c2"/>
                     <xsd:enumeration value="epr1am6tc1cr7c3"/>
                     <xsd:enumeration value="epr1am6tc1cr7c4"/>
                     <xsd:enumeration value="epr1am6tc1cr8c1"/>
                     <xsd:enumeration value="epr1am6tc1cr8c2"/>
                     <xsd:enumeration value="epr1am6tc1cr8c3"/>
                     <xsd:enumeration value="epr1am6tc1cr8c4"/>
                     <xsd:enumeration value="epr1am6tc1cr9c1"/>
                     <xsd:enumeration value="epr1am6tc1cr9c2"/>
                     <xsd:enumeration value="epr1am6tc1cr9c3"/>
                     <xsd:enumeration value="epr1am6tc1cr9c4"/>
                     <xsd:enumeration value="epr1am6tc1cr10c1"/>
                     <xsd:enumeration value="epr1am6tc1cr10c2"/>
                     <xsd:enumeration value="epr1am6tc1cr10c3"/>
                     <xsd:enumeration value="epr1am6tc1cr10c4"/>
                     <xsd:enumeration value="epr1am6tc1cr11c1"/>
                     <xsd:enumeration value="epr1am6tc1cr11c2"/>
                     <xsd:enumeration value="epr1am6tc1cr11c3"/>
                     <xsd:enumeration value="epr1am6tc1cr11c4"/>
                     <xsd:enumeration value="epr1am6tc1dr1c1"/>
                     <xsd:enumeration value="epr1am6tc1dr1c2"/>
                     <xsd:enumeration value="epr1am6tc1er1c1"/>
                     <xsd:enumeration value="epr1am6tc1er1c2"/>
                     <xsd:enumeration value="epr1am6tc1er2c1"/>
                     <xsd:enumeration value="epr1am6tc1er2c2"/>
                     <xsd:enumeration value="epr1am6tc1er3c1"/>
                     <xsd:enumeration value="epr1am6tc1er3c2"/>
                     <xsd:enumeration value="epr1am6tc1er4c1"/>
                     <xsd:enumeration value="epr1am6tc1er4c2"/>
                     <xsd:enumeration value="epr1am6tc1er5c1"/>
                     <xsd:enumeration value="epr1am6tc1er5c2"/>
                     <xsd:enumeration value="epr1am6tc1er6c1"/>
                     <xsd:enumeration value="epr1am6tc1er6c2"/>
                     <xsd:enumeration value="epr1am6tc1er7c1"/>
                     <xsd:enumeration value="epr1am6tc1er7c2"/>
                     <xsd:enumeration value="epr1am6tc1er8c1"/>
                     <xsd:enumeration value="epr1am6tc1er8c2"/>
                     <xsd:enumeration value="epr1am6tc1er9c1"/>
                     <xsd:enumeration value="epr1am6tc1er9c2"/>
                     <xsd:enumeration value="epr1am6tc1er10c1"/>
                     <xsd:enumeration value="epr1am6tc1er10c2"/>
                     <xsd:enumeration value="epr1am6tc1fr1c1"/>
                     <xsd:enumeration value="epr1am6tc1fr1c2"/>
                     <xsd:enumeration value="epr1am6tc2r1c1a"/>
                     <xsd:enumeration value="epr1am6tc2r1c1b"/>
                     <xsd:enumeration value="epr1am6tc2r1c1"/>
                     <xsd:enumeration value="epr1am6tc2r1c2"/>
                     <xsd:enumeration value="epr1am6tc2r2c1"/>
                     <xsd:enumeration value="epr1am6tc2r2c2"/>
                     <xsd:enumeration value="epr1am6tc2r3c1"/>
                     <xsd:enumeration value="epr1am6tc2r3c2"/>
                     <xsd:enumeration value="epr1am6tc2r4c1"/>
                     <xsd:enumeration value="epr1am6tc2r4c2"/>
                     <xsd:enumeration value="epr1am6tc2r5c1"/>
                     <xsd:enumeration value="epr1am6tc2r5c2"/>
                     <xsd:enumeration value="epr1am6tc2r6c1"/>
                     <xsd:enumeration value="epr1am6tc2r6c2"/>
                     <xsd:enumeration value="epr1am6tc2r7c1"/>
                     <xsd:enumeration value="epr1am6tc2r7c2"/>
                     <xsd:enumeration value="epr1am6tc2r7c3"/>
                     <xsd:enumeration value="epr1am6tc2r7c4"/>
                     <xsd:enumeration value="epr1am6tc2r8c4"/>
                     <xsd:enumeration value="epr1am6tc2r9c1"/>
                     <xsd:enumeration value="epr1am6tc2r9c2"/>
                     <xsd:enumeration value="epr1am6tc2r10c1"/>
                     <xsd:enumeration value="epr1am6tc2r10c2"/>
                     <xsd:enumeration value="epr1am6tc2r11c1"/>
                     <xsd:enumeration value="epr1am6tc2r11c2"/>
                     <xsd:enumeration value="epr1am6tc2r11bc1"/>
                     <xsd:enumeration value="epr1am6tc2r11bc2"/>
                     <xsd:enumeration value="epr1am6tc2r11bc3"/>
                     <xsd:enumeration value="epr1am6tc2r11bc4"/>
                     <xsd:enumeration value="epr1am6tc2r12c1"/>
                     <xsd:enumeration value="epr1am6tc2r12c2"/>
                     <xsd:enumeration value="epr1am6tc2r13c1"/>
                     <xsd:enumeration value="epr1am6tc2r13c2"/>
                     <xsd:enumeration value="epr1am6tc2r14c1"/>
                     <xsd:enumeration value="epr1am6tc2r14c2"/>
                     <xsd:enumeration value="epr1am6tc2r14c3"/>
                     <xsd:enumeration value="epr1am6tc2r14c4"/>
                     <xsd:enumeration value="epr1am6tc2r15c1"/>
                     <xsd:enumeration value="epr1am6tc2r15c2"/>
                     <xsd:enumeration value="epr1am6tc2r15c3"/>
                     <xsd:enumeration value="epr1am6tc2r15c4"/>
                     <xsd:enumeration value="epr1am6tc2r16c1"/>
                     <xsd:enumeration value="epr1am6tc2r16c2"/>
                     <xsd:enumeration value="epr1am6tc2r16c3"/>
                     <xsd:enumeration value="epr1am6tc2r16c4"/>
                     <xsd:enumeration value="epr1am6tc2r17c1"/>
                     <xsd:enumeration value="epr1am6tc2r17c2"/>
                     <xsd:enumeration value="epr1am6tc2r17c3"/>
                     <xsd:enumeration value="epr1am6tc2r17c4"/>
                     <xsd:enumeration value="epr1am6tc2r18c1"/>
                     <xsd:enumeration value="epr1am6tc2r18c2"/>
                     <xsd:enumeration value="epr1am6tc2r18c3"/>
                     <xsd:enumeration value="epr1am6tc2r18c4"/>
                     <xsd:enumeration value="epr1am6tc2r19c1"/>
                     <xsd:enumeration value="epr1am6tc2r19c2"/>
                     <xsd:enumeration value="epr1am6tc2r19c3"/>
                     <xsd:enumeration value="epr1am6tc2r19c4"/>
                     <xsd:enumeration value="epr1am6tc2r20c1"/>
                     <xsd:enumeration value="epr1am6tc2r20c2"/>
                     <xsd:enumeration value="epr1am6tc2r20c3"/>
                     <xsd:enumeration value="epr1am6tc2r20c4"/>
                     <xsd:enumeration value="epr1am6tc2r21c1"/>
                     <xsd:enumeration value="epr1am6tc2r21c2"/>
                     <xsd:enumeration value="epr1am6tc2r21c3"/>
                     <xsd:enumeration value="epr1am6tc2r21c4"/>
                     <xsd:enumeration value="epr1am6tc2r21bc1"/>
                     <xsd:enumeration value="epr1am6tc2r21bc2"/>
                     <xsd:enumeration value="epr1am6tc2r21bc3"/>
                     <xsd:enumeration value="epr1am6tc2r21bc4"/>
                     <xsd:enumeration value="epr1am6tc2r22c1"/>
                     <xsd:enumeration value="epr1am6tc2r22c2"/>
                     <xsd:enumeration value="epr1am6tc2r22c3"/>
                     <xsd:enumeration value="epr1am6tc2r22c4"/>
                     <xsd:enumeration value="epr1am6tc2r23c1"/>
                     <xsd:enumeration value="epr1am6tc2r23c2"/>
                     <xsd:enumeration value="epr1am6tc2r23c3"/>
                     <xsd:enumeration value="epr1am6tc2r23c4"/>
                     <xsd:enumeration value="epr1am6tc2r24c1"/>
                     <xsd:enumeration value="epr1am6tc2r24c2"/>
                     <xsd:enumeration value="epr1am6tc2r24c3"/>
                     <xsd:enumeration value="epr1am6tc2r24c4"/>
                     <xsd:enumeration value="epr1am6tc2r25c1"/>
                     <xsd:enumeration value="epr1am6tc2r25c2"/>
                     <xsd:enumeration value="epr1am6tc2r26c1"/>
                     <xsd:enumeration value="epr1am6tc2r26c2"/>
                     <xsd:enumeration value="epr1am6tc2r27c1"/>
                     <xsd:enumeration value="epr1am6tc2r27c2"/>
                     <xsd:enumeration value="epr1am6tc2r28c1"/>
                     <xsd:enumeration value="epr1am6tc2r28c2"/>
                     <xsd:enumeration value="epr1am6tc2r29c1"/>
                     <xsd:enumeration value="epr1am6tc2r29c2"/>
                     <xsd:enumeration value="epr1am6tc2r30c1"/>
                     <xsd:enumeration value="epr1am6tc2r30c2"/>
                     <xsd:enumeration value="epr1am6tc2r31c1"/>
                     <xsd:enumeration value="epr1am6tc2r31c2"/>
                     <xsd:enumeration value="epr1am6tc2r32c1"/>
                     <xsd:enumeration value="epr1am6tc2r32c2"/>
                     <xsd:enumeration value="epr1am6tc2r32bc1"/>
                     <xsd:enumeration value="epr1am6tc2r32bc2"/>
                     <xsd:enumeration value="epr1am6tc2r33c1"/>
                     <xsd:enumeration value="epr1am6tc2r33c2"/>
                     <xsd:enumeration value="epr1am6tc2r34c1"/>
                     <xsd:enumeration value="epr1am6tc2r34c2"/>
                     <xsd:enumeration value="epr1am6tc2r34c3"/>
                     <xsd:enumeration value="epr1am6tc2r34c4"/>
                     <xsd:enumeration value="epr1am6tc2r34c5"/>
                     <xsd:enumeration value="epr1am6tc2r34c6"/>
                     <xsd:enumeration value="epr1am6tc2r35c6"/>
                     <xsd:enumeration value="epr1am6tc2r36c4"/>
                     <xsd:enumeration value="epr1am6tc2r36c5"/>
                     <xsd:enumeration value="epr1am6tc2r38c1"/>
                     <xsd:enumeration value="epr1am6tc2r38c2"/>
                     <xsd:enumeration value="epr1am6tc2r39c1"/>
                     <xsd:enumeration value="epr1am6tc2r39c2"/>
                     <xsd:enumeration value="epr1am6tc2r40c1"/>
                     <xsd:enumeration value="epr1am6tc2r40c2"/>
                     <xsd:enumeration value="epr1am6tc2r41c1"/>
                     <xsd:enumeration value="epr1am6tc2r41c2"/>
                     <xsd:enumeration value="epr1am6tc2r42c1"/>
                     <xsd:enumeration value="epr1am6tc2r42c2"/>
                     <xsd:enumeration value="epr1am6tc2r43c1"/>
                     <xsd:enumeration value="epr1am6tc2r43c2"/>
                     <xsd:enumeration value="epr1am6tc3ar1c1"/>
                     <xsd:enumeration value="epr1am6tc3ar1c2"/>
                     <xsd:enumeration value="epr1am6tc3br1c1"/>
                     <xsd:enumeration value="epr1am6tc3br1c2"/>
                     <xsd:enumeration value="epr1am6tc3br2c1"/>
                     <xsd:enumeration value="epr1am6tc3br2c2"/>
                     <xsd:enumeration value="epr1am6tc3cr1c1"/>
                     <xsd:enumeration value="epr1am6tc3cr1c2"/>
                     <xsd:enumeration value="epr1am6tc3cr2c1"/>
                     <xsd:enumeration value="epr1am6tc3cr2c2"/>
                     <xsd:enumeration value="epr1am6tc3cr3c1"/>
                     <xsd:enumeration value="epr1am6tc3cr3c2"/>
                     <xsd:enumeration value="epr1am6tc3cr4c1"/>
                     <xsd:enumeration value="epr1am6tc3cr4c2"/>
                     <xsd:enumeration value="epr1am6tc3cr5c1"/>
                     <xsd:enumeration value="epr1am6tc3cr5c2"/>
                     <xsd:enumeration value="epr1am6tc3cr6c1"/>
                     <xsd:enumeration value="epr1am6tc3cr6c2"/>
                     <xsd:enumeration value="epr1am6tc3dr1c1"/>
                     <xsd:enumeration value="epr1am6tc3dr2c1"/>
                     <xsd:enumeration value="epr1am6tc3dr3c1"/>
                     <xsd:enumeration value="epr1am6tc3dr4c1"/>
                     <xsd:enumeration value="epr1am6tc3er1c1"/>
                     <xsd:enumeration value="epr1am6tc3er1c2"/>
                     <xsd:enumeration value="epr1am6tc3er1c3"/>
                     <xsd:enumeration value="epr1am6tc3er2c1"/>
                     <xsd:enumeration value="epr1am6tc3er2c2"/>
                     <xsd:enumeration value="epr1am6tc3er2c3"/>
                     <xsd:enumeration value="epr1am6tc3fr1c1"/>
                     <xsd:enumeration value="epr1am6tc3fr1c2"/>
                     <xsd:enumeration value="epr1am6tc3fr2c1"/>
                     <xsd:enumeration value="epr1am6tc3fr2c2"/>
                     <xsd:enumeration value="epr1am6tc3fr3c1"/>
                     <xsd:enumeration value="epr1am6tc3fr3ac2"/>
                     <xsd:enumeration value="epr1am6tc3fr3ac3"/>
                     <xsd:enumeration value="epr1am6tc3fr3ac4"/>
                     <xsd:enumeration value="epr1am6tc3fr3c5"/>
                     <xsd:enumeration value="epr1am6tc3fr3c6"/>
                     <xsd:enumeration value="epr1am6tc3fr3bc2"/>
                     <xsd:enumeration value="epr1am6tc3fr3bc3"/>
                     <xsd:enumeration value="epr1am6tc3fr3bc4"/>
                     <xsd:enumeration value="epr1am6tc3fr4c1"/>
                     <xsd:enumeration value="epr1am6tc3fr4ac2"/>
                     <xsd:enumeration value="epr1am6tc3fr4ac3"/>
                     <xsd:enumeration value="epr1am6tc3fr4ac4"/>
                     <xsd:enumeration value="epr1am6tc3fr4c5"/>
                     <xsd:enumeration value="epr1am6tc3fr4c6"/>
                     <xsd:enumeration value="epr1am6tc3fr4bc2"/>
                     <xsd:enumeration value="epr1am6tc3fr4bc3"/>
                     <xsd:enumeration value="epr1am6tc3fr4bc4"/>
                     <xsd:enumeration value="epr1am6tc3gr1c1"/>
                     <xsd:enumeration value="epr1am6tc3gr1c2"/>
                     <xsd:enumeration value="epr1am6tc3gr1c3"/>
                     <xsd:enumeration value="epr1am6tc3gr1c4"/>
                     <xsd:enumeration value="epr1am6tc3gr2c1"/>
                     <xsd:enumeration value="epr1am6tc3gr2c2"/>
                     <xsd:enumeration value="epr1am6tc3gr2c3"/>
                     <xsd:enumeration value="epr1am6tc3gr2c4"/>
                     <xsd:enumeration value="epr1am6tc3gr3c1"/>
                     <xsd:enumeration value="epr1am6tc3gr3c2"/>
                     <xsd:enumeration value="epr1am6tc3gr4c1"/>
                     <xsd:enumeration value="epr1am6tc3gr4c2"/>
                     <xsd:enumeration value="epr1am6tc3gr5c1"/>
                     <xsd:enumeration value="epr1am6tc3gr5c2"/>
                     <xsd:enumeration value="epr1am6tc3gr6c1"/>
                     <xsd:enumeration value="epr1am6tc3gr6c2"/>
                     <xsd:enumeration value="epr1am6tc3gr7ac1"/>
                     <xsd:enumeration value="epr1am6tc3gr7ac2"/>
                     <xsd:enumeration value="epr1am6tc3gr7ac3"/>
                     <xsd:enumeration value="epr1am6tc3gr7ac4"/>
                     <xsd:enumeration value="epr1am6tc3gr7c1"/>
                     <xsd:enumeration value="epr1am6tc3gr7c2"/>
                     <xsd:enumeration value="epr1am6tc3gr7c3"/>
                     <xsd:enumeration value="epr1am6tc3gr7c4"/>
                     <xsd:enumeration value="epr1am6tc3gr8c1"/>
                     <xsd:enumeration value="epr1am6tc3gr8c2"/>
                     <xsd:enumeration value="epr1am6tc3gr9c1"/>
                     <xsd:enumeration value="epr1am6tc3gr9c2"/>
                     <xsd:enumeration value="epr1am6tc3gr9c3"/>
                     <xsd:enumeration value="epr1am6tc3gr9c4"/>
                     <xsd:enumeration value="epr1am6tc3gr10c1"/>
                     <xsd:enumeration value="epr1am6tc3gr10c2"/>
                     <xsd:enumeration value="epr1am6tc3gr10c3"/>
                     <xsd:enumeration value="epr1am6tc3gr10c4"/>
                     <xsd:enumeration value="epr1am6tc3gr11c1"/>
                     <xsd:enumeration value="epr1am6tc3gr11c2"/>
                     <xsd:enumeration value="epr1am6tc3gr11c3"/>
                     <xsd:enumeration value="epr1am6tc3gr11c4"/>
                     <xsd:enumeration value="epr1am6tc3hr1c1"/>
                     <xsd:enumeration value="epr1am6tc3hr1c2"/>
                     <xsd:enumeration value="epr1am6tc3hr1c3"/>
                     <xsd:enumeration value="epr1am6tc3hr1c4"/>
                     <xsd:enumeration value="epr1am6tc3hr2c1"/>
                     <xsd:enumeration value="epr1am6tc3hr2c2"/>
                     <xsd:enumeration value="epr1am6tc3hr2c3"/>
                     <xsd:enumeration value="epr1am6tc3hr2c4"/>
                     <xsd:enumeration value="epr1am6tc3hr3c1"/>
                     <xsd:enumeration value="epr1am6tc3hr3c2"/>
                     <xsd:enumeration value="epr1am6tc3hr3c3"/>
                     <xsd:enumeration value="epr1am6tc3hr3c4"/>
                     <xsd:enumeration value="epr1am6tc3hr4c1"/>
                     <xsd:enumeration value="epr1am6tc3hr4c2"/>
                     <xsd:enumeration value="epr1am6tc3hr4c3"/>
                     <xsd:enumeration value="epr1am6tc3hr4c4"/>
                     <xsd:enumeration value="epr1am6tc3hr5c1"/>
                     <xsd:enumeration value="epr1am6tc3hr5c2"/>
                     <xsd:enumeration value="epr1am6tc3hr5c3"/>
                     <xsd:enumeration value="epr1am6tc3hr5c4"/>
                     <xsd:enumeration value="epr1am6tc3hr7c1"/>
                     <xsd:enumeration value="epr1am6tc3hr7c2"/>
                     <xsd:enumeration value="epr1am6tc3hr7c3"/>
                     <xsd:enumeration value="epr1am6tc3hr7c4"/>
                     <xsd:enumeration value="epr1am6tc3hr8c1"/>
                     <xsd:enumeration value="epr1am6tc3hr8c2"/>
                     <xsd:enumeration value="epr1am6tc3hr8c3"/>
                     <xsd:enumeration value="epr1am6tc3hr8c4"/>
                     <xsd:enumeration value="epr1am6tc3hr9c1"/>
                     <xsd:enumeration value="epr1am6tc3hr9c2"/>
                     <xsd:enumeration value="epr1am6tc3hr9c3"/>
                     <xsd:enumeration value="epr1am6tc3hr9c4"/>
                     <xsd:enumeration value="epr1am6tc3hr10c1"/>
                     <xsd:enumeration value="epr1am6tc3hr10c2"/>
                     <xsd:enumeration value="epr1am6tc3hr10c3"/>
                     <xsd:enumeration value="epr1am6tc3hr10c4"/>
                     <xsd:enumeration value="epr1am6tc3hr11c1"/>
                     <xsd:enumeration value="epr1am6tc3hr11c2"/>
                     <xsd:enumeration value="epr1am6tc3hr11c3"/>
                     <xsd:enumeration value="epr1am6tc3hr11c4"/>
                     <xsd:enumeration value="epr1am6tc3hr12c1"/>
                     <xsd:enumeration value="epr1am6tc3hr12c2"/>
                     <xsd:enumeration value="epr1am6tc3hr12c3"/>
                     <xsd:enumeration value="epr1am6tc3hr12c4"/>
                     <xsd:enumeration value="epr1am6tc3hr13c1"/>
                     <xsd:enumeration value="epr1am6tc3hr14c1"/>
                     <xsd:enumeration value="epr1am6tc3hr15c1"/>
                     <xsd:enumeration value="epr1am6tc3ir1c1"/>
                     <xsd:enumeration value="epr1am6tc3ir2c1"/>
                     <xsd:enumeration value="epr1am6tc3ir3c1"/>
                     <xsd:enumeration value="epr1am6tc3ir4c1"/>
                     <xsd:enumeration value="epr1am6tc3ir5c1"/>
                     <xsd:enumeration value="epr1am6tc3ir6c1"/>
                     <xsd:enumeration value="epr1am6tc3kr1c1"/>
                     <xsd:enumeration value="epr1am6tc3kr1c2"/>
                     <xsd:enumeration value="epr1am6tc3kr2c1"/>
                     <xsd:enumeration value="epr1am6tc3kr2c2"/>
                     <xsd:enumeration value="epr1am6tc3kr3c1"/>
                     <xsd:enumeration value="epr1am6tc3kr6c1"/>
                     <xsd:enumeration value="epr1am6tc3kr6c2"/>
                     <xsd:enumeration value="epr1am6tc3kr6c3"/>
                     <xsd:enumeration value="epr1am6tc3kr6c4"/>
                     <xsd:enumeration value="epr1am6tc3kr6c5"/>
                     <xsd:enumeration value="epr1am6tc3kr4c1"/>
                     <xsd:enumeration value="epr1am6tc3kr5c1"/>
                     <xsd:enumeration value="epr1am6ter1c1"/>
                     <xsd:enumeration value="epr1am6ter2c1"/>
                     <xsd:enumeration value="epr1am6ter2c2"/>
                     <xsd:enumeration value="epr1am6ter3c1"/>
                     <xsd:enumeration value="epr1am6ter3c2"/>
                     <xsd:enumeration value="epr1am6ter4c1"/>
                     <xsd:enumeration value="epr1am6ter4c2"/>
                     <xsd:enumeration value="epr1am6ter5c1"/>
                     <xsd:enumeration value="epr1am6ter5c2"/>
                     <xsd:enumeration value="epr1am6ter6c1"/>
                     <xsd:enumeration value="epr1am6ter6c2"/>
                     <xsd:enumeration value="epr1am6ter7c1"/>
                     <xsd:enumeration value="epr1am6ter7c2"/>
                     <xsd:enumeration value="epr1am6ter8c1"/>
                     <xsd:enumeration value="epr1am6ter8c2"/>
                     <xsd:enumeration value="epr1am6ter9c1"/>
                     <xsd:enumeration value="epr1am6ter9c2"/>
                     <xsd:enumeration value="epr1am6ter10c1"/>
                     <xsd:enumeration value="epr1am6ter10c2"/>
                     <xsd:enumeration value="epr1am6ter10bc1"/>
                     <xsd:enumeration value="epr1am6ter11c1"/>
                     <xsd:enumeration value="epr1am6ter12c1"/>
                     <xsd:enumeration value="epr1am6ter13c1"/>
                     <xsd:enumeration value="epr1am6ter13c2"/>
                     <xsd:enumeration value="epr1am6ter14c1"/>
                     <xsd:enumeration value="epr1am6ter14c2"/>
                     <xsd:enumeration value="epr1am6ter15c1"/>
                     <xsd:enumeration value="epr1am6ter15c2"/>
                     <xsd:enumeration value="epr1am6ter16c1"/>
                     <xsd:enumeration value="epr1am6ter16c2"/>
                     <xsd:enumeration value="epr1am6ter19c1"/>
                     <xsd:enumeration value="epr1am6ter19c2"/>
                     <xsd:enumeration value="epr1am6ter19bc1"/>
                     <xsd:enumeration value="epr1am6ter19bc2"/>
                     <xsd:enumeration value="epr1am6ter19cc1"/>
                     <xsd:enumeration value="epr1am6ter19cc2"/>
                     <xsd:enumeration value="epr1am6ter20c1"/>
                     <xsd:enumeration value="epr1am6ter20c2"/>
                     <xsd:enumeration value="epr1am6ter21c1"/>
                     <xsd:enumeration value="epr1am6ter21c2"/>
                     <xsd:enumeration value="epr1am6ter22c1"/>
                     <xsd:enumeration value="epr1am6ter22c2"/>
                     <xsd:enumeration value="epr1am6ter23c1"/>
                     <xsd:enumeration value="epr1am6ter23c2"/>
                     <xsd:enumeration value="epr1am6ter24c1"/>
                     <xsd:enumeration value="epr1am6ter25c1"/>
                     <xsd:enumeration value="epr1am6ter26c1"/>
                     <xsd:enumeration value="epr1am6ter27c1"/>
                     <xsd:enumeration value="epr1am6ter28c1"/>
                     <xsd:enumeration value="epr1am6ter29c1"/>
                     <xsd:enumeration value="epr1am6ter30c1"/>
                     <xsd:enumeration value="epr1am6ter31c1"/>
                     <xsd:enumeration value="epr1am6ter32c1"/>
                     <xsd:enumeration value="epr1am6ter32c2"/>
                     <xsd:enumeration value="epr1am6ter33c1"/>
                     <xsd:enumeration value="epr1am6ter33c2"/>
                     <xsd:enumeration value="epr1am6ter33c3"/>
                     <xsd:enumeration value="epr1am6ter34c1"/>
                     <xsd:enumeration value="epr1am6ter34c2"/>
                     <xsd:enumeration value="epr1am6ter34c3"/>
                     <xsd:enumeration value="epr1am6ter35c1"/>
                     <xsd:enumeration value="epr1am6ter35c2"/>
                     <xsd:enumeration value="epr1am6ter36c1"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
   
   <xsd:complexType name="epr1a2024GridKeyValuePairType">
      <xsd:annotation>
         <xsd:documentation xml:lang="EL">Ορισμός τύπου για την αναπαράσταση ζεύγους της μορφής κωδικός πεδίου - τιμή για την απεικόνιση κάθε πεδίου της δήλωσης Τ.Φ.1 Αυτεργοδοτούμενου 2024 το οποίο περιέχεται σε πίνακα.</xsd:documentation>
      </xsd:annotation>
      <xsd:simpleContent>
         <xsd:extension base="olive:notNullStringType">
            <xsd:attribute name="key" use="required">
               <xsd:annotation>
                  <xsd:documentation xml:lang="EL">Αναπαριστά τον κωδικό του πεδίου σε πίνακα της δήλωσης Τ.Φ.1 Αυτεργοδοτούμενου 2024. Οι επιτρεπτές τιμές αναφέρονται στην ακόλουθη λίστα</xsd:documentation>
               </xsd:annotation>
               <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                     <xsd:enumeration value="epr1am4ta3r1c1"/>
                     <xsd:enumeration value="epr1am4ta3r1c1b"/>
                     <xsd:enumeration value="epr1am4ta3r1c2"/>
                     <xsd:enumeration value="epr1am4ta3r1c2a"/>
                     <xsd:enumeration value="epr1am4ta3r1c2b"/>
                     <xsd:enumeration value="epr1am4ta3r1c3"/>
                     <xsd:enumeration value="epr1am4ta3r1c4"/>
                     <xsd:enumeration value="epr1am4ta3r1c5"/>
                     <xsd:enumeration value="epr1am4ta3r1c6"/>
                     <xsd:enumeration value="epr1am4ta3r1c7"/>
                     <xsd:enumeration value="epr1am4ta3r1c7b"/>
                     <xsd:enumeration value="epr1am4tbr1c1"/>
                     <xsd:enumeration value="epr1am4tbr1c2"/>
                     <xsd:enumeration value="epr1am4tbr1c3"/>
                     <xsd:enumeration value="epr1am4tbr1c4"/>
                     <xsd:enumeration value="epr1am4tbr1c5"/>
                     <xsd:enumeration value="epr1am4tbr1c6"/>
                     <xsd:enumeration value="epr1am4tcr1c1"/>
                     <xsd:enumeration value="epr1am4tcr1c2"/>
                     <xsd:enumeration value="epr1am4tcr1c3"/>
                     <xsd:enumeration value="epr1am4tcr1c4"/>
                     <xsd:enumeration value="epr1am4tcr1c5"/>
                     <xsd:enumeration value="epr1am4tcr1c6"/>
                     <xsd:enumeration value="epr1am4tcr1c7"/>
                     <xsd:enumeration value="epr1am4tcr1c8"/>
                     <xsd:enumeration value="epr1am4tcr1c9"/>
                     <xsd:enumeration value="epr1am4tcr1c9a"/>
                     <xsd:enumeration value="epr1am4tcr1c10"/>
                     <xsd:enumeration value="epr1am4tcr1c11"/>
                     <xsd:enumeration value="epr1am4tcr1c12"/>
                     <xsd:enumeration value="epr1am4tcr1c13"/>
                     <xsd:enumeration value="epr1am4tcr1c15"/>
                     <xsd:enumeration value="epr1am4tcr1c16"/>
                     <xsd:enumeration value="epr1am4tcr1c17"/>
                     <xsd:enumeration value="epr1am4tdr1c1"/>
                     <xsd:enumeration value="epr1am4tdr1c2"/>
                     <xsd:enumeration value="epr1am4tdr1c3"/>
                     <xsd:enumeration value="epr1am4tdr1c4"/>
                     <xsd:enumeration value="epr1am4tdr1c5"/>
                     <xsd:enumeration value="epr1am4tdr1c6"/>
                     <xsd:enumeration value="epr1am4tdr1c7"/>
                     <xsd:enumeration value="epr1am4tdr1c8"/>
                     <xsd:enumeration value="epr1am4tdr1c9"/>
                     <xsd:enumeration value="epr1am4tdr1c10"/>
                     <xsd:enumeration value="epr1am4tdr1c11"/>
                     <xsd:enumeration value="epr1am4tdr1c12"/>
                     <xsd:enumeration value="epr1am4tdr1c13"/>
                     <xsd:enumeration value="epr1am4tdr1c14"/>
                     <xsd:enumeration value="epr1am4tdr1c15"/>
                     <xsd:enumeration value="epr1am4tdr1c16"/>
                     <xsd:enumeration value="epr1am4ter1c1"/>
                     <xsd:enumeration value="epr1am4ter1c2"/>
                     <xsd:enumeration value="epr1am4ter1c3"/>
                     <xsd:enumeration value="epr1am4ter1c5"/>
                     <xsd:enumeration value="epr1am4ter1c6"/>
                     <xsd:enumeration value="epr1am4ter1c7"/>
                     <xsd:enumeration value="epr1am4ter1c7a"/>
                     <xsd:enumeration value="epr1am4ter1c8"/>
                     <xsd:enumeration value="epr1am4ter1c9"/>
                     <xsd:enumeration value="epr1am4ter1c10"/>
                     <xsd:enumeration value="epr1am4ter1c11"/>
                     <xsd:enumeration value="epr1am4tzr1c1"/>
                     <xsd:enumeration value="epr1am4tzr1c1b"/>
                     <xsd:enumeration value="epr1am4tzr1c2"/>
                     <xsd:enumeration value="epr1am4tzr1c3"/>
                     <xsd:enumeration value="epr1am4tzr1c4"/>
                     <xsd:enumeration value="epr1am4tzr1c5"/>
                     <xsd:enumeration value="epr1am4tzr1c5a"/>
                     <xsd:enumeration value="epr1am4tzr1c6"/>
                     <xsd:enumeration value="epr1am4tzr1c7"/>
                     <xsd:enumeration value="epr1am4thr1c1"/>
                     <xsd:enumeration value="epr1am4thr1c2"/>
                     <xsd:enumeration value="epr1am4thr1c3"/>
                     <xsd:enumeration value="epr1am4thr1c4"/>
                     <xsd:enumeration value="epr1am4thr1c5"/>
                     <xsd:enumeration value="epr1am4tjr1c1"/>
					 <xsd:enumeration value="epr1am4tjr1c2"/>
					 <xsd:enumeration value="epr1am4tjr1c3"/>
					 <xsd:enumeration value="epr1am4tjr1c4"/>
					 <xsd:enumeration value="epr1am4tjr1c5"/>
					 <xsd:enumeration value="epr1am4tjr1c6"/>
					 <xsd:enumeration value="epr1am4tjr1c7"/>
					 <xsd:enumeration value="epr1am4tjr1c8"/>
                     <xsd:enumeration value="epr1am4tur1c1"/>
                     <xsd:enumeration value="epr1am4tur1c2"/>
                     <xsd:enumeration value="epr1am4tur1c3"/>
                     <xsd:enumeration value="epr1am4tur1c3b"/>
                     <xsd:enumeration value="epr1am4tur1c4"/>
                     <xsd:enumeration value="epr1am4tur1c5"/>
                     <xsd:enumeration value="epr1am4tur1c6"/>
                     <xsd:enumeration value="epr1am4tur1c7"/>
                     <xsd:enumeration value="epr1am4tur1c8"/>
                     <xsd:enumeration value="epr1am4tur1c9"/>
                     <xsd:enumeration value="epr1am5tcr1c1"/>
                     <xsd:enumeration value="epr1am5tcr1c1b"/>
                     <xsd:enumeration value="epr1am5tcr1c1c"/>
                     <xsd:enumeration value="epr1am5tcr1c1d"/>
                     <xsd:enumeration value="epr1am5tcr1c2"/>
                     <xsd:enumeration value="epr1am5tcr1c3"/>
                     <xsd:enumeration value="epr1am5tcr1c4"/>
                     <xsd:enumeration value="epr1am5tcr1c5"/>
                     <xsd:enumeration value="epr1am5tdr1c1"/>
                     <xsd:enumeration value="epr1am5tdr1c2"/>
                     <xsd:enumeration value="epr1am5tdr1c3"/>
                     <xsd:enumeration value="epr1am5tdr1c4"/>
                     <xsd:enumeration value="epr1am5tdr1c5"/>
                     <xsd:enumeration value="epr1am5tdr1c6"/>
                     <xsd:enumeration value="epr1am5tdr1c7"/>
                     <xsd:enumeration value="epr1am5tdr2c1"/>
                     <xsd:enumeration value="epr1am5tdr2c2"/>
                     <xsd:enumeration value="epr1am5tdr2c3"/>
                     <xsd:enumeration value="epr1am5tdr2c4"/>
                     <xsd:enumeration value="epr1am5tdr2c5"/>
                     <xsd:enumeration value="epr1am5tdr2c6"/>
                     <xsd:enumeration value="epr1am5tdr2c7"/>
                     <xsd:enumeration value="epr1am6tar3c1"/>
                     <xsd:enumeration value="epr1am6tar3c2"/>
                     <xsd:enumeration value="epr1am6tc3fr5ac1"/>
                     <xsd:enumeration value="epr1am6tc3fr5bc1"/>
                     <xsd:enumeration value="epr1am6tc3fr5c2"/>
                     <xsd:enumeration value="epr1am6tc3fr5c3"/>
                     <xsd:enumeration value="epr1am6tc3fr5ac4"/>
                     <xsd:enumeration value="epr1am6tc3fr5bc4"/>
                     <xsd:enumeration value="epr1am6tc3fr5ac5"/>
                     <xsd:enumeration value="epr1am6tc3fr5bc5"/>
                     <xsd:enumeration value="epr1am6tc3fr5ac6"/>
                     <xsd:enumeration value="epr1am6tc3fr5bc6"/>
                     <xsd:enumeration value="epr1am6tc3fr5c7"/>
                     <xsd:enumeration value="epr1am6tc3fr5c8"/>
                     <xsd:enumeration value="epr1am6tc3jr1c1"/>
                     <xsd:enumeration value="epr1am6tc3jr1c2"/>
                     <xsd:enumeration value="epr1am6tc3jr1c3"/>
                     <xsd:enumeration value="epr1am6tc3jr1c4"/>
                     <xsd:enumeration value="epr1am6tc3jr1c5"/>
                     <xsd:enumeration value="epr1am6tc3jr1c6"/>
                     <xsd:enumeration value="epr1am6tc3jr1c7"/>
                  </xsd:restriction>
               </xsd:simpleType>
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
	
</xsd:schema>
